# AIVA Go Analysis CLI Commands
# Auto-generated by go2mermaid

## Category: OTHER
# [PLACEHOLDER] main 功能
go run services\scan\go_engine\cmd\cspm-scanner\main.go --func=main

# [PLACEHOLDER] main 功能
go run services\scan\go_engine\cmd\sca-scanner\main.go --func=main

# [PLACEHOLDER] getSSRFPayloads 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=getSSRFPayloads

# [PLACEHOLDER] containsSensitiveContent 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=containsSensitiveContent

# [PLACEHOLDER] extractParams 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=extractParams

# [PLACEHOLDER] setHeaders 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=setHeaders

# [PLACEHOLDER] truncateString 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=truncateString

# [PLACEHOLDER] main 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=main

# [PLACEHOLDER] outputResult 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=outputResult

# [PLACEHOLDER] outputError 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=outputError


## Category: RECONNAISSANCE
# [PLACEHOLDER] NewSSRFScanner 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=NewSSRFScanner

# [PLACEHOLDER] SSRFScanner.Scan 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.Scan

# [PLACEHOLDER] SSRFScanner.getBaseline 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.getBaseline

# [PLACEHOLDER] SSRFScanner.testPayload 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.testPayload

# [PLACEHOLDER] SSRFScanner.analyzeResponse 功能
go run services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.analyzeResponse


