flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;根據工具類型獲取對應的 Topic\n\n        Args:\n        ...]
    n4[topic_map = &#123;&amp;&#35;39;function_sqli&amp;&#35;39;...]
    n5[return topic_map.get&#40;tool_type, Topic...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2