# AIVA Go Analysis CLI Commands
# Auto-generated by go2mermaid

## Category: OTHER
# [PLACEHOLDER] main 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\cmd\worker\main.go --func=main

# [PLACEHOLDER] DialBroker 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=DialBroker

# [PLACEHOLDER] Broker.Subscribe 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=Broker.Subscribe

# [PLACEHOLDER] Broker.Publish 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=Broker.Publish

# [PLACEHOLDER] Broker.Close 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=Broker.Close

# [PLACEHOLDER] Broker.PublishFinding 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=Broker.PublishFinding

# [PLACEHOLDER] Broker.PublishStatus 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=Broker.PublishStatus

# [PLACEHOLDER] TopicFromEnv 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=TopicFromEnv

# [PLACEHOLDER] MustEnv 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=MustEnv

# [PLACEHOLDER] Debugf 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\amqp.go --func=Debugf

# [PLACEHOLDER] DefaultConfig 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\config.go --func=DefaultConfig

# [PLACEHOLDER] NewAuthnEngine 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\engine.go --func=NewAuthnEngine

# [PLACEHOLDER] AuthnEngine.RunTests 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\engine.go --func=AuthnEngine.RunTests

# [PLACEHOLDER] AuthnEngine.testWeakPassword 功能
go run c:\D\fold7\AIVA-git\services\features\features_in_development\function_authn_go\internal\engine.go --func=AuthnEngine.testWeakPassword


