# AIVA TypeScript Analysis CLI Commands
# Auto-generated by ts2mermaid

## Category: ANALYSIS
# [PLACEHOLDER] DOMSecurityAnalyzer.analyze in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.analyze"

# [PLACEHOLDER] DOMSecurityAnalyzer.analyzeSourceToSink in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.analyzeSourceToSink"

# [PLACEHOLDER] DOMSecurityAnalyzer.analyzePostMessage in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.analyzePostMessage"

# [PLACEHOLDER] DOMSecurityAnalyzer.analyzeDOMClobbering in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.analyzeDOMClobbering"

# [PLACEHOLDER] DOMSecurityAnalyzer.analyzeWebSocket in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.analyzeWebSocket"

# [PLACEHOLDER] DOMSecurityAnalyzer.analyzeSPARoutes in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.analyzeSPARoutes"

# [PLACEHOLDER] DOMSecurityAnalyzer.getFindings in dom-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/dom-security-analyzer.ts" --func "DOMSecurityAnalyzer.getFindings"

# [PLACEHOLDER] NetworkInterceptor.analyzeRequestPatterns in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.analyzeRequestPatterns"

# [PLACEHOLDER] SPAStateCrawler.analyzeAPIEndpoints in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.analyzeAPIEndpoints"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.analyze in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.analyze"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.discoverRoutes in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.discoverRoutes"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.testRouteTraversal in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.testRouteTraversal"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.testClientSideBypass in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.testClientSideBypass"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.testUnauthorizedAccess in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.testUnauthorizedAccess"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.getFindings in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.getFindings"

# [PLACEHOLDER] WebSocketSecurityAnalyzer.analyze in websocket-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/websocket-security-analyzer.ts" --func "WebSocketSecurityAnalyzer.analyze"

# [PLACEHOLDER] WebSocketSecurityAnalyzer.injectWebSocketMonitor in websocket-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/websocket-security-analyzer.ts" --func "WebSocketSecurityAnalyzer.injectWebSocketMonitor"

# [PLACEHOLDER] WebSocketSecurityAnalyzer.analyzeConnection in websocket-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/websocket-security-analyzer.ts" --func "WebSocketSecurityAnalyzer.analyzeConnection"

# [PLACEHOLDER] WebSocketSecurityAnalyzer.containsSensitiveData in websocket-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/websocket-security-analyzer.ts" --func "WebSocketSecurityAnalyzer.containsSensitiveData"

# [PLACEHOLDER] WebSocketSecurityAnalyzer.getFindings in websocket-security-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/websocket-security-analyzer.ts" --func "WebSocketSecurityAnalyzer.getFindings"

## Category: OTHER
# [PLACEHOLDER] initialize in index.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/index.ts" --func "initialize"

# [PLACEHOLDER] consumeTasks in index.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/index.ts" --func "consumeTasks"

# [PLACEHOLDER] shutdown in index.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/index.ts" --func "shutdown"

# [PLACEHOLDER] main in index.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/index.ts" --func "main"

# [PLACEHOLDER] EnhancedContentExtractor.extractAll in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractAll"

# [PLACEHOLDER] EnhancedContentExtractor.extractForms in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractForms"

# [PLACEHOLDER] EnhancedContentExtractor.extractDynamicLinks in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractDynamicLinks"

# [PLACEHOLDER] EnhancedContentExtractor.extractAjaxEndpoints in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractAjaxEndpoints"

# [PLACEHOLDER] EnhancedContentExtractor.extractApiCalls in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractApiCalls"

# [PLACEHOLDER] EnhancedContentExtractor.extractWebSockets in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractWebSockets"

# [PLACEHOLDER] EnhancedContentExtractor.extractJSVariables in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractJSVariables"

# [PLACEHOLDER] EnhancedContentExtractor.extractEventListeners in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.extractEventListeners"

# [PLACEHOLDER] EnhancedContentExtractor.getExtractionStats in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.getExtractionStats"

# [PLACEHOLDER] EnhancedContentExtractor.clear in enhanced-content-extractor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-content-extractor.service.ts" --func "EnhancedContentExtractor.clear"

# [PLACEHOLDER] InteractionSimulator.executeAll in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.executeAll"

# [PLACEHOLDER] InteractionSimulator.setupDOMObserver in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.setupDOMObserver"

# [PLACEHOLDER] InteractionSimulator.simulateButtonClicks in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.simulateButtonClicks"

# [PLACEHOLDER] InteractionSimulator.simulateFormFilling in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.simulateFormFilling"

# [PLACEHOLDER] InteractionSimulator.simulateScrolling in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.simulateScrolling"

# [PLACEHOLDER] InteractionSimulator.simulateHovering in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.simulateHovering"

# [PLACEHOLDER] InteractionSimulator.simulateKeyboardEvents in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.simulateKeyboardEvents"

# [PLACEHOLDER] InteractionSimulator.getElementSelector in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.getElementSelector"

# [PLACEHOLDER] InteractionSimulator.getTestValueForInput in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.getTestValueForInput"

# [PLACEHOLDER] InteractionSimulator.captureDOMChanges in interaction-simulator.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/interaction-simulator.service.ts" --func "InteractionSimulator.captureDOMChanges"

# [PLACEHOLDER] NetworkInterceptor.startInterception in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.startInterception"

# [PLACEHOLDER] NetworkInterceptor.removeListeners in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.removeListeners"

# [PLACEHOLDER] NetworkInterceptor.stopInterception in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.stopInterception"

# [PLACEHOLDER] NetworkInterceptor.getRequests in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.getRequests"

# [PLACEHOLDER] NetworkInterceptor.getApiRequests in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.getApiRequests"

# [PLACEHOLDER] NetworkInterceptor.getAjaxRequests in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.getAjaxRequests"

# [PLACEHOLDER] NetworkInterceptor.getWebSocketRequests in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.getWebSocketRequests"

# [PLACEHOLDER] NetworkInterceptor.isLikelyApiEndpoint in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.isLikelyApiEndpoint"

# [PLACEHOLDER] NetworkInterceptor.clear in network-interceptor.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/network-interceptor.service.ts" --func "NetworkInterceptor.clear"

# [PLACEHOLDER] SPAStateCrawler.crawlStates in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.crawlStates"

# [PLACEHOLDER] SPAStateCrawler.crawlRecursive in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.crawlRecursive"

# [PLACEHOLDER] SPAStateCrawler.extractState in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.extractState"

# [PLACEHOLDER] SPAStateCrawler.findInteractableElements in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.findInteractableElements"

# [PLACEHOLDER] SPAStateCrawler.setupAPIInterceptor in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.setupAPIInterceptor"

# [PLACEHOLDER] SPAStateCrawler.normalizeURL in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.normalizeURL"

## Category: RECONNAISSANCE
# [PLACEHOLDER] DOMXSSDetector.interceptSinks in enhanced-dom-xss-detector.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dom-xss-detector.service.ts" --func "DOMXSSDetector.interceptSinks"

# [PLACEHOLDER] DOMXSSDetector.testDOMXSS in enhanced-dom-xss-detector.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dom-xss-detector.service.ts" --func "DOMXSSDetector.testDOMXSS"

# [PLACEHOLDER] DOMXSSDetector.testMultipleInjectionPoints in enhanced-dom-xss-detector.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dom-xss-detector.service.ts" --func "DOMXSSDetector.testMultipleInjectionPoints"

# [PLACEHOLDER] DOMXSSDetector.discoverInjectionPoints in enhanced-dom-xss-detector.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dom-xss-detector.service.ts" --func "DOMXSSDetector.discoverInjectionPoints"

# [PLACEHOLDER] DOMXSSDetector.generatePayloads in enhanced-dom-xss-detector.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dom-xss-detector.service.ts" --func "DOMXSSDetector.generatePayloads"

# [PLACEHOLDER] EnhancedDynamicScanService.executeDynamicScan in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.executeDynamicScan"

# [PLACEHOLDER] EnhancedDynamicScanService.shouldSimulateInteractions in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.shouldSimulateInteractions"

# [PLACEHOLDER] EnhancedDynamicScanService.collectJavaScriptErrors in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.collectJavaScriptErrors"

# [PLACEHOLDER] EnhancedDynamicScanService.extractDOMChangesFromInteractions in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.extractDOMChangesFromInteractions"

# [PLACEHOLDER] EnhancedDynamicScanService.countDOMChanges in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.countDOMChanges"

# [PLACEHOLDER] EnhancedDynamicScanService.deduplicateContents in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.deduplicateContents"

# [PLACEHOLDER] EnhancedDynamicScanService.getServiceStats in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.getServiceStats"

# [PLACEHOLDER] EnhancedDynamicScanService.healthCheck in enhanced-dynamic-scan.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/enhanced-dynamic-scan.service.ts" --func "EnhancedDynamicScanService.healthCheck"

# [PLACEHOLDER] ScanService.normalizeUrl in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.normalizeUrl"

# [PLACEHOLDER] ScanService.scan in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.scan"

# [PLACEHOLDER] ScanService.extractAssets in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.extractAssets"

# [PLACEHOLDER] ScanService.extractLinks in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.extractLinks"

# [PLACEHOLDER] ScanService.setupWebSocketMonitoring in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.setupWebSocketMonitoring"

# [PLACEHOLDER] ScanService.setupSpaMonitoring in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.setupSpaMonitoring"

# [PLACEHOLDER] ScanService.detectSpaFramework in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.detectSpaFramework"

# [PLACEHOLDER] ScanService.extractSpaRoutes in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.extractSpaRoutes"

# [PLACEHOLDER] ScanService.extractNetworkAssets in scan-service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/scan-service.ts" --func "ScanService.extractNetworkAssets"

# [PLACEHOLDER] SPAStateCrawler.detectAccessControlIssues in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.detectAccessControlIssues"

# [PLACEHOLDER] SPARouteSecurityAnalyzer.detectSPAFramework in spa-route-analyzer.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/spa-route-analyzer.ts" --func "SPARouteSecurityAnalyzer.detectSPAFramework"

## Category: REPORTING
# [PLACEHOLDER] SPAStateCrawler.generateStateGraph in spa-state-crawler.service.ts
npx ts-node ts2mermaid.ts --file "C:/D/fold7/AIVA-git/services/scan/typescript_engine/src/services/spa-state-crawler.service.ts" --func "SPAStateCrawler.generateStateGraph"

