line-length = 88
target-version = "py311"
fix = true

[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "C4", "PIE", "W"]
ignore = ["E501"]  # handled by black

[lint.isort]
known-first-party = ["services"]
force-sort-within-sections = true

[lint.per-file-ignores]
"tests/*" = ["F401", "F811"]  # allow unused imports in tests
"__init__.py" = ["F401"]  # allow unused imports in __init__.py

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Path"]