flowchart TB
    n1([開始])
    n2([結束])
    n3[lines = &#91;f&amp;&#35;39;&#123;self.method&#125; &#123;...]
    n4{if &amp;&#35;39;headers&amp;&#35;39; in self.request_k...}
    n5{for &#40;key, value&#41; in self.request_kwar...}
    n6[lines.append&#40;f&amp;&#35;39;&#123;key&#125;: &#123;val...]
    n7[]
    n8[]
    n9[body_parts = &#91;&#93;]
    n10{if &amp;&#35;39;params&amp;&#35;39; in self.request_kw...}
    n11[body_parts.append&#40;f&amp;quot;params=&#123;self.reques...]
    n12[]
    n13{if &amp;&#35;39;data&amp;&#35;39; in self.request_kwargs}
    n14[body_parts.append&#40;f&amp;quot;data=&#123;self.request_...]
    n15[]
    n16{if &amp;&#35;39;json&amp;&#35;39; in self.request_kwargs}
    n17[body_parts.append&#40;f&amp;quot;json=&#123;self.request_...]
    n18[]
    n19{if &amp;&#35;39;content&amp;&#35;39; in self.request_k...}
    n20[body_parts.append&#40;f&amp;quot;content=&#123;self.reque...]
    n21[]
    n22{if body_parts}
    n23[lines.append&#40;&amp;&#35;39;\n&amp;&#35;39;.join&#40;bo...]
    n24[]
    n25[return &amp;&#35;39;\n&amp;&#35;39;.join&#40;lines&#41;]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n8
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n5
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 -->|Yes| n11
    n10 -->|No| n12
    n11 --> n12
    n12 --> n13
    n13 -->|Yes| n14
    n13 -->|No| n15
    n14 --> n15
    n15 --> n16
    n16 -->|Yes| n17
    n16 -->|No| n18
    n17 --> n18
    n18 --> n19
    n19 -->|Yes| n20
    n19 -->|No| n21
    n20 --> n21
    n21 --> n22
    n22 -->|Yes| n23
    n22 -->|No| n24
    n23 --> n24
    n24 --> n25
    n25 --> n2