flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;Scale global rate by a factor.&amp;&#35;39;]
    n4{if factor &amp;lt;= 0}
    n5[return]
    n6[]
    n7[self._set_global_rate&#40;self.global_rps * factor&#41;]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n2