flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;Get the rate limit for a specific host.&amp;...]
    n4[return self.host_overrides.get&#40;host, ...]
    n1 --> n3
    n3 --> n4
    n4 --> n2