flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        Adjust global and per-host rates b...]
    n4[self._touch_host&#40;host&#41;]
    n5[global_penalty = 1.0]
    n6[host_penalty = 1.0]
    n7[base_penalty = 1.0]
    n8[global_boost = 1.0]
    n9[host_boost = 1.0]
    n10[base_boost = 1.0]
    n11[ra_until = None]
    n12[try]
    n13{if headers and any&#40;&#40;k.lower&#40;&#41; ...}
    n14[ra_val = next&#40;&#40;headers&#91;k&#93; for...]
    n15{if ra_val is not None}
    n16[ra_val = str&#40;ra_val&#41;.strip&#40;&#41;]
    n17{if re.fullmatch&#40;&amp;&#35;39;\\d+&amp;&#35;39;, ra_va...}
    n18[ra_until = time.monotonic&#40;&#41; + f...]
    n19[try]
    n20[dt = parsedate_to_datetim...]
    n21[ra_until = time.monotonic&#40;&#41; + m...]
    n22[]
    n23[except &#40;ValueError,...]
    n24[self._log.debug&#40;&amp;&#35;39;Failed to parse HTTP-dat...]
    n25[ra_until = None]
    n26[]
    n27[]
    n28[]
    n29[]
    n30[except &#40;KeyError, A...]
    n31[self._log.debug&#40;&amp;&#35;39;Failed to process Retry-...]
    n32[ra_until = None]
    n33{if ra_until is not None}
    n34[prev = self._cooldown_until...]
    n35[self._cooldown_until&#91;host&#93; = max&#40;prev or 0.0,...]
    n36[with contextli...]
    n37[self._log.info&#40;&amp;&#35;39;ratelimiter.cooldown_begi...]
    n38[base_penalty *= 1.5]
    n39[host_penalty *= 2.0]
    n40[]
    n41{if status_code is not None}
    n42{if status_code == 429}
    n43[global_penalty = min&#40;global_penalty, ...]
    n44[host_penalty = min&#40;host_penalty, 0....]
    n45[base_penalty = min&#40;base_penalty, 0....]
    n46{if status_code in &#123;503, 504&#125;}
    n47[global_penalty = min&#40;global_penalty, ...]
    n48[host_penalty = min&#40;host_penalty, 0....]
    n49[base_penalty = min&#40;base_penalty, 0....]
    n50{if 500 &amp;lt;= status_code &amp;lt; 600}
    n51[global_penalty = min&#40;global_penalty, ...]
    n52[host_penalty = min&#40;host_penalty, 0....]
    n53[base_penalty = min&#40;base_penalty, 0....]
    n54{if 200 &amp;lt;= status_code &amp;lt; 300}
    n55[global_boost = max&#40;global_boost, 1....]
    n56[host_boost = max&#40;host_boost, 1.08...]
    n57[base_boost = max&#40;base_boost, 1.02...]
    n58[]
    n59[]
    n60[]
    n61[]
    n62[]
    n63{if latency is not None}
    n64{if latency &amp;gt; 5.0}
    n65[global_penalty = min&#40;global_penalty, ...]
    n66[host_penalty = min&#40;host_penalty, 0....]
    n67[base_penalty = min&#40;base_penalty, 0....]
    n68{if latency &amp;gt; 2.5}
    n69[global_penalty = min&#40;global_penalty, ...]
    n70[host_penalty = min&#40;host_penalty, 0....]
    n71[base_penalty = min&#40;base_penalty, 0....]
    n72{if latency &amp;lt; 0.3}
    n73[global_boost = max&#40;global_boost, 1....]
    n74[host_boost = max&#40;host_boost, 1.1&#41;]
    n75[base_boost = max&#40;base_boost, 1.04...]
    n76{if latency &amp;lt; 0.6}
    n77[global_boost = max&#40;global_boost, 1....]
    n78[host_boost = max&#40;host_boost, 1.05...]
    n79[base_boost = max&#40;base_boost, 1.02...]
    n80[]
    n81[]
    n82[]
    n83[]
    n84[]
    n85{if global_penalty &amp;lt; 1.0 or hos...}
    n86{if global_penalty &amp;lt; 1.0}
    n87[self._scale_global&#40;global_penalty&#41;]
    n88[]
    n89{if base_penalty &amp;lt; 1.0}
    n90[self._scale_per_host_base&#40;base_penalty&#41;]
    n91[]
    n92{if host_penalty &amp;lt; 1.0}
    n93[self._scale_host&#40;host, host_penalty&#41;]
    n94[]
    n95[return]
    n96[]
    n97{if global_boost &amp;gt; 1.0}
    n98[self._scale_global&#40;global_boost&#41;]
    n99[]
    n100{if base_boost &amp;gt; 1.0}
    n101[self._scale_per_host_base&#40;base_boost&#41;]
    n102[]
    n103{if host_boost &amp;gt; 1.0}
    n104[self._scale_host&#40;host, host_boost&#41;]
    n105[]
    n106[try]
    n107{if status_code and 200 &amp;lt;= int&#40;...}
    n108[until = self._cooldown_until...]
    n109{if until}
    n110[now = time.monotonic&#40;&#41;]
    n111{if now + max&#40;0.0, latency&#41; * 2...}
    n112[self._cooldown_until.pop&#40;host, None&#41;]
    n113[self._log.info&#40;&amp;&#35;39;ratelimiter.cooldown_end ...]
    n114[]
    n115[]
    n116[]
    n117[]
    n118[except &#40;KeyError, V...]
    n119[self._log.debug&#40;&amp;&#35;39;Error processing respons...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n11
    n11 --> n12
    n12 --> n13
    n12 --> n30
    n13 -->|Yes| n14
    n13 -->|No| n28
    n14 --> n15
    n15 -->|Yes| n16
    n15 -->|No| n27
    n16 --> n17
    n17 -->|Yes| n18
    n17 -->|No| n19
    n18 --> n26
    n19 --> n20
    n19 --> n23
    n20 --> n21
    n21 --> n22
    n22 --> n26
    n23 --> n24
    n24 --> n25
    n25 --> n22
    n26 --> n27
    n27 --> n28
    n28 --> n29
    n29 --> n33
    n30 --> n31
    n31 --> n32
    n32 --> n29
    n33 -->|Yes| n34
    n33 -->|No| n40
    n34 --> n35
    n35 --> n36
    n36 --> n37
    n37 --> n38
    n38 --> n39
    n39 --> n40
    n40 --> n41
    n41 -->|Yes| n42
    n41 -->|No| n62
    n42 -->|Yes| n43
    n42 -->|No| n46
    n43 --> n44
    n44 --> n45
    n45 --> n61
    n46 -->|Yes| n47
    n46 -->|No| n50
    n47 --> n48
    n48 --> n49
    n49 --> n60
    n50 -->|Yes| n51
    n50 -->|No| n54
    n51 --> n52
    n52 --> n53
    n53 --> n59
    n54 -->|Yes| n55
    n54 -->|No| n58
    n55 --> n56
    n56 --> n57
    n57 --> n58
    n58 --> n59
    n59 --> n60
    n60 --> n61
    n61 --> n62
    n62 --> n63
    n63 -->|Yes| n64
    n63 -->|No| n84
    n64 -->|Yes| n65
    n64 -->|No| n68
    n65 --> n66
    n66 --> n67
    n67 --> n83
    n68 -->|Yes| n69
    n68 -->|No| n72
    n69 --> n70
    n70 --> n71
    n71 --> n82
    n72 -->|Yes| n73
    n72 -->|No| n76
    n73 --> n74
    n74 --> n75
    n75 --> n81
    n76 -->|Yes| n77
    n76 -->|No| n80
    n77 --> n78
    n78 --> n79
    n79 --> n80
    n80 --> n81
    n81 --> n82
    n82 --> n83
    n83 --> n84
    n84 --> n85
    n85 -->|Yes| n86
    n85 -->|No| n96
    n86 -->|Yes| n87
    n86 -->|No| n88
    n87 --> n88
    n88 --> n89
    n89 -->|Yes| n90
    n89 -->|No| n91
    n90 --> n91
    n91 --> n92
    n92 -->|Yes| n93
    n92 -->|No| n94
    n93 --> n94
    n94 --> n95
    n95 --> n96
    n96 --> n97
    n97 -->|Yes| n98
    n97 -->|No| n99
    n98 --> n99
    n99 --> n100
    n100 -->|Yes| n101
    n100 -->|No| n102
    n101 --> n102
    n102 --> n103
    n103 -->|Yes| n104
    n103 -->|No| n105
    n104 --> n105
    n105 --> n106
    n106 --> n107
    n106 --> n118
    n107 -->|Yes| n108
    n107 -->|No| n116
    n108 --> n109
    n109 -->|Yes| n110
    n109 -->|No| n115
    n110 --> n111
    n111 -->|Yes| n112
    n111 -->|No| n114
    n112 --> n113
    n113 --> n114
    n114 --> n115
    n115 --> n116
    n116 --> n117
    n117 --> n2
    n118 --> n119
    n119 --> n117