flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;計算額外動作數量\n\n        Args:\n            match...]
    n4[return sum&#40;&#40;1 for m in matches if m.m...]
    n1 --> n3
    n3 --> n4
    n4 --> n2