flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;評估目標達成\n\n        Args:\n            plan: 攻...]
    n4{if completion_rate &amp;lt; 0.8 or su...}
    n5[return False]
    n6[]
    n7{if plan.attack_type.value in &#123;...}
    n8[has_findings = any&#40;&#40;trace.output_da...]
    n9{if not has_findings}
    n10[return False]
    n11[]
    n12[]
    n13[return self._check_critical_steps&#40;pla...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 -->|Yes| n8
    n7 -->|No| n12
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n11
    n11 --> n12
    n12 --> n13
    n13 --> n2