flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取 RAG 引擎統計信息\n\n        Returns:\n         ...]
    n4[return &#123;&amp;&#35;39;knowledge_base&amp;&#35;39;: se...]
    n1 --> n3
    n3 --> n4
    n4 --> n2