flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;主程式進入點.&amp;&#35;39;]
    n4[import argparse]
    n5[parser = argparse.ArgumentPar...]
    n6[parser.add_argument&#40;&amp;&#35;39;--mode&amp;&#35;39;,...]
    n7[parser.add_argument&#40;&amp;&#35;39;--host&amp;&#35;39;,...]
    n8[parser.add_argument&#40;&amp;&#35;39;--ports&amp;&#35;39;...]
    n9[args = parser.parse_args&#40;&#41;]
    n10[start_auto_server&#40;mode=args.mode, host=args.host, ...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n2