flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;完成會話\n\n        Args:\n            session_i...]
    n4[self.update_session_status&#40;session_id, &amp;&#35;39;c...]
    n1 --> n3
    n3 --> n4
    n4 --> n2