flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;生成指標鍵值&amp;&#35;39;]
    n4{if not labels}
    n5[return name]
    n6[]
    n7[label_str = &amp;&#35;39;_&amp;&#35;39;.join&#40;&#40;f&a...]
    n8[return f&amp;&#35;39;&#123;name&#125;_&#123;hash&#40;labe...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2