flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;驗證 URL 格式.&amp;&#35;39;]
    n4{if not v.startswith&#40;&#40;&amp;&#35;39;http://&amp;&#3...}
    n5[raise ValueError&#40;&amp;&#35;39;URL must start with htt...]
    n6[]
    n7[return v]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n2