flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\nAIVA Core - 核心引擎模組\n\n這是 AIVA 的核心處理引擎，負責協調...]
    n4[__version__ = &amp;&#35;39;1.0.0&amp;&#35;39;]
    n5[from services.aiva_common.enums import ComplianceF...]
    n6[from services.aiva_common.schemas import CVERefere...]
    n7[from services.core.ai_models import AIExperienceCr...]
    n8[from services.core.models import AttackPathEdge, A...]
    n9[__all__ = &#91;&amp;&#35;39;CVEReference&amp;&#35;39;, &a...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n2