flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;記錄錯誤\n\n        Args:\n            context: ...]
    n4[self.trace_recorder.record_error&#40;trace_session_id=...]
    n1 --> n3
    n3 --> n4
    n4 --> n2