flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;格式化狀態消息\n\n        Args:\n            status...]
    n4[return f&amp;quot;\n當前系統狀態：\n- 操作模式: &#123;status&#91;&am...]
    n1 --> n3
    n3 --> n4
    n4 --> n2