flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;歸還組件到池中&amp;&#35;39;]
    n4{if hasattr&#40;component, &amp;&#35;39;reset&amp;&#35;39;...}
    n5[component.reset&#40;&#41;]
    n6[]
    n7[try]
    n8[self.pool.put_nowait&#40;component&#41;]
    n9[self.active_components.discard&#40;id&#40;component&#41;&...]
    n10[]
    n11[except asyncio.Queu...]
    n12[pass]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n7 --> n11
    n8 --> n9
    n9 --> n10
    n10 --> n2
    n11 --> n12
    n12 --> n10