flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        獲取用戶的所有權限\n\n        Args:\n      ...]
    n4[user_roles = self.get_user_roles&#40;...]
    n5[all_permissions = &#91;&#93;]
    n6{for role in user_roles}
    n7[role_permissions = self.matrix.get_role...]
    n8{for perm in role_permissions}
    n9[all_permissions.append&#40;&#123;**perm, &amp;&#35;39;via...]
    n10[]
    n11[]
    n12[logger.debug&#40;&amp;&#35;39;user_all_permissions_retrie...]
    n13[return all_permissions]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 -->|Yes| n7
    n6 -->|No| n11
    n7 --> n8
    n8 -->|Yes| n9
    n8 -->|No| n10
    n9 --> n8
    n10 --> n6
    n11 --> n12
    n12 --> n13
    n13 --> n2