flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        初始化視覺化器\n\n        Args:\n        ...]
    n4[self.matrix = permission_matrix]
    n5[logger.info&#40;&amp;&#35;39;matrix_visualizer_initialize...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2