flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;結束軌跡記錄\n\n        Args:\n            trace_s...]
    n4[trace = self.active_traces.g...]
    n5{if trace}
    n6[trace.finalize&#40;&#41;]
    n7[logger.info&#40;f&amp;&#35;39;Finalized trace session &#1...]
    n8[return trace]
    n9[]
    n10[return None]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n9
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n2