flowchart TB
    n1([開始])
    n2([結束])
    n3[cond = f&amp;&#35;39; &#91;&#123;self.condition&#125;...]
    n4[return f&amp;&#35;39;&#123;self.from_node&#125; -&amp;gt;...]
    n1 --> n3
    n3 --> n4
    n4 --> n2