flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;批次前向傳播\n\n        Args:\n            X: 輸入批次...]
    n4[predictions = &#91;&#93;]
    n5{for x in X}
    n6[pred = self.model.forward&#40;x...]
    n7[predictions.append&#40;np.max&#40;pred&#41;&#41;]
    n8[]
    n9[return np.array&#40;predictions&#41;]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n8
    n6 --> n7
    n7 --> n5
    n8 --> n9
    n9 --> n2