flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取會話狀態\n\n        Args:\n            session...]
    n4[return self.active_sessions.get&#40;sessi...]
    n1 --> n3
    n3 --> n4
    n4 --> n2