flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;保存訓練會話\n\n        Args:\n            session...]
    n4{if session_id is None}
    n5{for session in self.training_ses...}
    n6[self._save_single_session&#40;session&#41;]
    n7[]
    n8[session = next&#40;&#40;s for s in sel...]
    n9{if session}
    n10[self._save_single_session&#40;session&#41;]
    n11[]
    n12[]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n8
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n5
    n7 --> n12
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n11
    n11 --> n12
    n12 --> n2