flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;標記會話為失敗\n\n        Args:\n            sessio...]
    n4[self.update_session_status&#40;session_id, &amp;&#35;39;f...]
    n1 --> n3
    n3 --> n4
    n4 --> n2