flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;開始監控執行計畫\n\n        Args:\n            plan:...]
    n4[trace_metadata = &#123;&amp;&#35;39;plan_id&amp;&#35;39;:...]
    n5[trace = self.trace_recorder....]
    n6[logger.info&#40;f&amp;&#35;39;Started monitoring plan &#1...]
    n7[return trace]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n2