flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取訓練摘要\n\n        Returns:\n            訓練摘要...]
    n4[return &#123;&amp;&#35;39;config&amp;&#35;39;: &#123;&amp...]
    n1 --> n3
    n3 --> n4
    n4 --> n2