flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取系統狀態\n\n        Returns:\n            狀態信息...]
    n4[return &#123;&amp;&#35;39;mode&amp;&#35;39;: self.current...]
    n1 --> n3
    n3 --> n4
    n4 --> n2