flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        獲取角色的所有權限\n\n        Args:\n      ...]
    n4[permissions = &#91;&#93;]
    n5{for &#40;&#40;r, resource, permission&#41;, decision&#41;...}
    n6{if r == role}
    n7[permissions.append&#40;&#123;&amp;&#35;39;resource&amp;&#...]
    n8[]
    n9[]
    n10[logger.debug&#40;&amp;&#35;39;role_permissions_retrieved&...]
    n11[return permissions]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n9
    n6 -->|Yes| n7
    n6 -->|No| n8
    n7 --> n8
    n8 --> n5
    n9 --> n10
    n10 --> n11
    n11 --> n2