flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;驗證模型\n\n        Args:\n            X: 驗證特徵\n...]
    n4[predictions = self._forward_batch&#40;...]
    n5[loss = np.mean&#40;&#40;predictions...]
    n6[accuracy = np.sum&#40;np.abs&#40;predic...]
    n7[return &#40;loss, accuracy&#41;]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n2