flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;初始化數據加載器\n\n        Args:\n            exper...]
    n4[self.repository = experience_repositor...]
    n5[logger.info&#40;&amp;&#35;39;ExperienceDataLoader initial...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2