flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取知識庫統計.\n\n        Returns:\n            知識...]
    n4[return &#123;&amp;&#35;39;total_chunks&amp;&#35;39;: self...]
    n1 --> n3
    n3 --> n4
    n4 --> n2