flowchart TB
    n1([開始])
    n2([結束])
    n3[service_map = &#123;21: &amp;&#35;39;FTP&amp;&#35;39;, 22...]
    n4[return service_map.get&#40;port, f&amp;&#35;39;Unknow...]
    n1 --> n3
    n3 --> n4
    n4 --> n2