flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        執行完整的持久化檢查\n\n        Returns:\n  ...]
    n4[logger.info&#40;&amp;&#35;39;persistence_assessment_start...]
    n5[assessment = &#123;&amp;&#35;39;assessment_id&amp;&#35;39...]
    n6[assessment&#91;&amp;&#35;39;tests&amp;&#35;39;&#93;.appen...]
    n7[assessment&#91;&amp;&#35;39;tests&amp;&#35;39;&#93;.appen...]
    n8[assessment&#91;&amp;&#35;39;tests&amp;&#35;39;&#93;.appen...]
    n9{if self.os_type == &amp;&#35;39;Windows&amp;&#35;39;}
    n10[assessment&#91;&amp;&#35;39;tests&amp;&#35;39;&#93;.appen...]
    n11[assessment&#91;&amp;&#35;39;tests&amp;&#35;39;&#93;.appen...]
    n12[]
    n13[total_findings = sum&#40;&#40;len&#40;test.get&#40;&amp;&...]
    n14[assessment&#91;&amp;&#35;39;summary&amp;&#35;39;&#93; = &...]
    n15[logger.info&#40;&amp;&#35;39;persistence_assessment_compl...]
    n16[return assessment]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n12
    n11 --> n12
    n12 --> n13
    n13 --> n14
    n14 --> n15
    n15 --> n16
    n16 --> n2