flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;Generate advanced XSS payloads for testing.&...]
    n4[return self.generate&#40;payload_sets=&#91;&amp;&#35;39;a...]
    n1 --> n3
    n3 --> n4
    n4 --> n2