flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取評分最高的經驗記錄\n\n        Args:\n            at...]
    n4[return self.query_experiences&#40;attack_...]
    n1 --> n3
    n3 --> n4
    n4 --> n2