flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        SAST-DAST 資料流關聯分析\n        \n     ...]
    n4{if not findings}
    n5[return &#123;&amp;&#35;39;confirmed_flows&amp;&#35;39;: &...]
    n6[]
    n7[sast_findings = &#91;&#93;]
    n8[dast_findings = &#91;&#93;]
    n9{for finding in findings}
    n10[scan_type = finding.get&#40;&amp;&#35;39;scan_ty...]
    n11[vuln_type = finding.get&#40;&amp;&#35;39;vulnera...]
    n12{if scan_type == &amp;&#35;39;sast&amp;&#35;39; or &amp;&#...}
    n13[sast_findings.append&#40;finding&#41;]
    n14{if scan_type == &amp;&#35;39;dast&amp;&#35;39; or &amp;&#...}
    n15[dast_findings.append&#40;finding&#41;]
    n16[]
    n17[]
    n18[]
    n19[confirmed_flows = &#91;&#93;]
    n20[unconfirmed_sast = list&#40;sast_findings&#41;]
    n21[orphan_dast = list&#40;dast_findings&#41;]
    n22{for sast_finding in sast_findings}
    n23[sast_location = sast_finding.get&#40;&amp;&#35;39;lo...]
    n24[sast_vuln_type = sast_finding.get&#40;&amp;&#35;39;vu...]
    n25{for dast_finding in dast_findings}
    n26[dast_location = dast_finding.get&#40;&amp;&#35;39;lo...]
    n27[dast_vuln_type = dast_finding.get&#40;&amp;&#35;39;vu...]
    n28{if self._are_vulnerability_typ...}
    n29{if self._check_path_correlatio...}
    n30[confirmed_flow = &#123;&amp;&#35;39;sast_finding_id&amp;&...]
    n31[confirmed_flows.append&#40;confirmed_flow&#41;]
    n32{if sast_finding in unconfirmed...}
    n33[unconfirmed_sast.remove&#40;sast_finding&#41;]
    n34[]
    n35{if dast_finding in orphan_dast}
    n36[orphan_dast.remove&#40;dast_finding&#41;]
    n37[]
    n38[]
    n39[]
    n40[]
    n41[]
    n42[logger.info&#40;f&amp;&#35;39;SAST-DAST correlation: &#12...]
    n43[return &#123;&amp;&#35;39;confirmed_flows&amp;&#35;39;: c...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n18
    n10 --> n11
    n11 --> n12
    n12 -->|Yes| n13
    n12 -->|No| n14
    n13 --> n17
    n14 -->|Yes| n15
    n14 -->|No| n16
    n15 --> n16
    n16 --> n17
    n17 --> n9
    n18 --> n19
    n19 --> n20
    n20 --> n21
    n21 --> n22
    n22 -->|Yes| n23
    n22 -->|No| n41
    n23 --> n24
    n24 --> n25
    n25 -->|Yes| n26
    n25 -->|No| n40
    n26 --> n27
    n27 --> n28
    n28 -->|Yes| n29
    n28 -->|No| n39
    n29 -->|Yes| n30
    n29 -->|No| n38
    n30 --> n31
    n31 --> n32
    n32 -->|Yes| n33
    n32 -->|No| n34
    n33 --> n34
    n34 --> n35
    n35 -->|Yes| n36
    n35 -->|No| n37
    n36 --> n37
    n37 --> n38
    n38 --> n39
    n39 --> n25
    n40 --> n22
    n41 --> n42
    n42 --> n43
    n43 --> n2