flowchart TB
    n1([開始])
    n2([結束])
    n3[result = whois_query&#40;domain&#41;]
    n4{if result}
    n5[return &#123;&amp;&#35;39;registrar&amp;&#35;39;: getattr...]
    n6[]
    n7[return &#123;&amp;&#35;39;error&amp;&#35;39;: &amp;&#35;3...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n2