flowchart TB
    n1([開始])
    n2([結束])
    n3[from __future__ import annotations]
    n4[import asyncio]
    n5[from typing import Any]
    n6[from fastapi import FastAPI, HTTPException]
    n7[from services.aiva_common.enums import Topic]
    n8[from services.aiva_common.mq import get_broker]
    n9[from services.aiva_common.schemas import AivaMessa...]
    n10[from services.aiva_common.utils import get_logger]
    n11[from .analysis.compliance_policy_checker import Co...]
    n12[from .analysis.risk_assessment_engine import RiskA...]
    n13[from .analysis.vuln_correlation_analyzer import Vu...]
    n14[from .config_template.config_template_manager impo...]
    n15[from .perf_feedback.improvement_suggestion_generat...]
    n16[from .perf_feedback.scan_metadata_analyzer import ...]
    n17[from .reception.data_reception_layer import DataRe...]
    n18[from .reception.test_result_database import TestRe...]
    n19[from .reporting.formatter_exporter import Formatte...]
    n20[from .reporting.report_content_generator import Re...]
    n21[from .reporting.report_template_selector import Re...]
    n22[app = FastAPI&#40;title=&amp;&#35;39;AIVA ...]
    n23[logger = get_logger&#40;__name__&#41;]
    n24[db = TestResultDatabase&#40;&#41;]
    n25[recv = DataReceptionLayer&#40;d...]
    n26[corr = VulnerabilityCorrela...]
    n27[risk = RiskAssessmentEngine...]
    n28[comp = CompliancePolicyChec...]
    n29[rptgen = ReportContentGenerat...]
    n30[fmt = FormatterExporter&#40;&#41;]
    n31[rptsel = ReportTemplateSelect...]
    n32[smeta = ScanMetadataAnalyzer...]
    n33[impr = ImprovementSuggestio...]
    n34[ctm = ConfigTemplateManage...]
    n35[def startup&#40;...&#41;]
    n36[def get_finding&#40;...&#41;]
    n37[def _consume_logs&#40;...&#41;]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n11
    n11 --> n12
    n12 --> n13
    n13 --> n14
    n14 --> n15
    n15 --> n16
    n16 --> n17
    n17 --> n18
    n18 --> n19
    n19 --> n20
    n20 --> n21
    n21 --> n22
    n22 --> n23
    n23 --> n24
    n24 --> n25
    n25 --> n26
    n26 --> n27
    n27 --> n28
    n28 --> n29
    n29 --> n30
    n30 --> n31
    n31 --> n32
    n32 --> n33
    n33 --> n34
    n34 --> n35
    n35 --> n36
    n36 --> n37
    n37 --> n2