flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取經過的時間（秒）&amp;&#35;39;]
    n4{if self.duration is not None}
    n5[return self.duration]
    n6[]
    n7{if self.start_time is not None}
    n8[return time.perf_counter&#40;&#41; - self.sta...]
    n9[]
    n10[return 0.0]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 -->|Yes| n8
    n7 -->|No| n9
    n8 --> n9
    n9 --> n10
    n10 --> n2