flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        估算修復後的風險降低程度\n\n        Returns:\n...]
    n4[risk_score = path.total_risk_scor...]
    n5{if risk_score &amp;gt;= 25}
    n6[return 95.0]
    n7{if risk_score &amp;gt;= 15}
    n8[return 85.0]
    n9{if risk_score &amp;gt;= 8}
    n10[return 70.0]
    n11[return 50.0]
    n12[]
    n13[]
    n14[]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n14
    n7 -->|Yes| n8
    n7 -->|No| n9
    n8 --> n13
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n12
    n11 --> n12
    n12 --> n13
    n13 --> n14
    n14 --> n2