flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;提取受影響的資產&amp;&#35;39;]
    n4[assets = &#91;&#93;]
    n5{for node in path.nodes}
    n6{if &amp;&#35;39;Asset&amp;&#35;39; in node.get&#40;&amp;&...}
    n7[asset_value = node.get&#40;&amp;&#35;39;value&amp;&#35;39...]
    n8[assets.append&#40;asset_value&#41;]
    n9[]
    n10[]
    n11[return assets]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n10
    n6 -->|Yes| n7
    n6 -->|No| n9
    n7 --> n8
    n8 --> n9
    n9 --> n5
    n10 --> n11
    n11 --> n2