flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;轉換 FindingPayload 為字典&amp;&#35;39;]
    n4[return &#123;&amp;&#35;39;finding_id&amp;&#35;39;: findin...]
    n1 --> n3
    n3 --> n4
    n4 --> n2