flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        獲取技術的緩解措施\n\n        Args:\n      ...]
    n4{if not self.attack_data}
    n5[return &#91;&#93;]
    n6[]
    n7[try]
    n8[techniques = self.attack_data.get...]
    n9[technique_obj = None]
    n10{for tech in techniques}
    n11[external_refs = tech.get&#40;&amp;&#35;39;external_r...]
    n12{for ref in external_refs}
    n13{if ref.get&#40;&amp;&#35;39;source_name&amp;&#35;39;&#41;...}
    n14[technique_obj = tech]
    n15[break]
    n16[]
    n17[]
    n18{if technique_obj}
    n19[break]
    n20[]
    n21[]
    n22{if not technique_obj}
    n23[return &#91;&#93;]
    n24[]
    n25[tech_id_raw = technique_obj.get&#40;&amp;&#35;39;i...]
    n26{if not tech_id_raw or not isin...}
    n27[return &#91;&#93;]
    n28[]
    n29[tech_id: str = tech_id_raw]
    n30[mitigations = self.attack_data.get...]
    n31[results = &#91;&#93;]
    n32{for mitigation in mitigations}
    n33[external_refs = mitigation.get&#40;&amp;&#35;39;exte...]
    n34[mitigation_id = None]
    n35{for ref in external_refs}
    n36{if ref.get&#40;&amp;&#35;39;source_name&amp;&#35;39;&#41;...}
    n37[mitigation_id = ref.get&#40;&amp;&#35;39;external_id...]
    n38[break]
    n39[]
    n40[]
    n41[results.append&#40;&#123;&amp;&#35;39;id&amp;&#35;39;: mi...]
    n42[]
    n43[logger.info&#40;&amp;&#35;39;mitigations_retrieved&amp;&#...]
    n44[return results]
    n45[]
    n46[except Exception]
    n47[logger.error&#40;&amp;&#35;39;get_mitigations_failed&amp;...]
    n48[return &#91;&#93;]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n7 --> n46
    n8 --> n9
    n9 --> n10
    n10 -->|Yes| n11
    n10 -->|No| n21
    n11 --> n12
    n12 -->|Yes| n13
    n12 -->|No| n17
    n13 -->|Yes| n14
    n13 -->|No| n16
    n14 --> n15
    n15 --> n16
    n16 --> n12
    n17 --> n18
    n18 -->|Yes| n19
    n18 -->|No| n20
    n19 --> n20
    n20 --> n10
    n21 --> n22
    n22 -->|Yes| n23
    n22 -->|No| n24
    n23 --> n24
    n24 --> n25
    n25 --> n26
    n26 -->|Yes| n27
    n26 -->|No| n28
    n27 --> n28
    n28 --> n29
    n29 --> n30
    n30 --> n31
    n31 --> n32
    n32 -->|Yes| n33
    n32 -->|No| n42
    n33 --> n34
    n34 --> n35
    n35 -->|Yes| n36
    n35 -->|No| n40
    n36 -->|Yes| n37
    n36 -->|No| n39
    n37 --> n38
    n38 --> n39
    n39 --> n35
    n40 --> n41
    n41 --> n32
    n42 --> n43
    n43 --> n44
    n44 --> n45
    n45 --> n2
    n46 --> n47
    n47 --> n48
    n48 --> n45