flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取指定瀏覽器的詳細信息&amp;&#35;39;]
    n4[browser_instance = self._browsers.get&#40;b...]
    n5{if not browser_instance}
    n6[return None]
    n7[]
    n8[return &#123;&amp;&#35;39;browser_id&amp;&#35;39;: browse...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n7
    n7 --> n8
    n8 --> n2