flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;列出所有頁面實例信息&amp;&#35;39;]
    n4[pages_info = &#91;&#93;]
    n5{for page_instance in self._pages.values&#40;&#41;}
    n6[pages_info.append&#40;&#123;&amp;&#35;39;page_id&amp;&#35...]
    n7[]
    n8[return pages_info]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n5
    n7 --> n8
    n8 --> n2