flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\nAIVA Scan - 掃描模組\n\n這是 AIVA 的掃描模組包，負責目標發現、...]
    n4[__version__ = &amp;&#35;39;1.0.0&amp;&#35;39;]
    n5[from ..aiva_common.enums import AssetType, ScanSta...]
    n6[from ..aiva_common.schemas import CVEReference, CV...]
    n7[from .models import Asset, AssetInventoryItem, Ass...]
    n8[__all__ = &#91;&amp;&#35;39;AssetType&amp;&#35;39;, &amp;...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2