flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        創建隱秘模式配置（模擬真實瀏覽器）\n\n        Retur...]
    n4[config = cls&#40;user_headers=&#123;&amp;&#35;39;A...]
    n5[return config]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2