flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        移除允許的主機\n\n        Args:\n        ...]
    n4{if hostname in self._allowed_h...}
    n5[self._allowed_hosts_set.remove&#40;hostname&#41;]
    n6{if hostname in self.scope.allo...}
    n7[self.scope.allowed_hosts.remove&#40;hostname&#41;]
    n8[]
    n9[logger.info&#40;f&amp;&#35;39;Removed allowed host: &#123...]
    n10[]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n10
    n5 --> n6
    n6 -->|Yes| n7
    n6 -->|No| n8
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n2