flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        合併另一個範圍管理器的配置\n\n        Args:\n  ...]
    n4{for host in other.get_allowed...}
    n5[self.add_allowed_host&#40;host&#41;]
    n6[]
    n7{for exclusion in other.get_exclusi...}
    n8{if exclusion not in self.scope...}
    n9[self.add_exclusion&#40;exclusion&#41;]
    n10[]
    n11[]
    n12{if other.is_subdomain_included...}
    n13[self.set_include_subdomains&#40;True&#41;]
    n14[]
    n15[logger.info&#40;&amp;&#35;39;Merged scope configurations&...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n4
    n6 --> n7
    n7 -->|Yes| n8
    n7 -->|No| n11
    n8 -->|Yes| n9
    n8 -->|No| n10
    n9 --> n10
    n10 --> n7
    n11 --> n12
    n12 -->|Yes| n13
    n12 -->|No| n14
    n13 --> n14
    n14 --> n15
    n15 --> n2