flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;初始化 JavaScript 分析器&amp;&#35;39;]
    n4[self.analysis_results: list&#91;JavaScriptAnalysisResu...]
    n5[logger.debug&#40;&amp;&#35;39;JavaScriptAnalyzer initiali...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2