flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        獲取統計信息\n\n        Returns:\n      ...]
    n4{if not self.analysis_results}
    n5[return &#123;&amp;&#35;39;total_files&amp;&#35;39;: 0, &a...]
    n6[]
    n7[total_score = sum&#40;&#40;r.security_scor...]
    n8[total_dangerous = sum&#40;&#40;len&#40;r.dangerous...]
    n9[total_leaks = sum&#40;&#40;len&#40;r.data_leak...]
    n10[return &#123;&amp;&#35;39;total_files&amp;&#35;39;: len&#...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n2