# AIVA Go Analysis CLI Commands
# Auto-generated by go2mermaid

## Category: ANALYSIS
# 自動分析: analysis 模組中的 Stitcher.AnalyzeBranches 功能
go run go2mermaid.go --func=Stitcher.AnalyzeBranches


## Category: OTHER
# 自動分析: other 模組中的 NewStitcher 功能
go run go2mermaid.go --func=NewStitcher

# 自動分析: other 模組中的 Stitcher.AddScript 功能
go run go2mermaid.go --func=Stitcher.AddScript

# 自動分析: other 模組中的 Stitcher.ResolveConnections 功能
go run go2mermaid.go --func=Stitcher.ResolveConnections

# 自動分析: other 模組中的 Stitcher.findProviderInPackage 功能
go run go2mermaid.go --func=Stitcher.findProviderInPackage

# 自動分析: other 模組中的 NewClassifier 功能
go run go2mermaid.go --func=NewClassifier

# 自動分析: other 模組中的 Classifier.Classify 功能
go run go2mermaid.go --func=Classifier.Classify

# 自動分析: other 模組中的 Classifier.GetResult 功能
go run go2mermaid.go --func=Classifier.GetResult

# 自動分析: other 模組中的 NewBuilder 功能
go run go2mermaid.go --func=NewBuilder

# 自動分析: other 模組中的 Builder.BuildFunction 功能
go run go2mermaid.go --func=Builder.BuildFunction

# 自動分析: other 模組中的 Builder.buildStmt 功能
go run go2mermaid.go --func=Builder.buildStmt

# 自動分析: other 模組中的 Builder.inspectBlock 功能
go run go2mermaid.go --func=Builder.inspectBlock

# 自動分析: other 模組中的 Builder.inspectStmt 功能
go run go2mermaid.go --func=Builder.inspectStmt

# 自動分析: other 模組中的 Builder.inspectExpr 功能
go run go2mermaid.go --func=Builder.inspectExpr

# 自動分析: other 模組中的 getFunctionName 功能
go run go2mermaid.go --func=getFunctionName

# 自動分析: other 模組中的 NewGraph 功能
go run go2mermaid.go --func=NewGraph

# 自動分析: other 模組中的 Graph.Add 功能
go run go2mermaid.go --func=Graph.Add

# 自動分析: other 模組中的 Graph.Link 功能
go run go2mermaid.go --func=Graph.Link

# 自動分析: other 模組中的 Graph.ToMermaid 功能
go run go2mermaid.go --func=Graph.ToMermaid

# 自動分析: other 模組中的 formatNode 功能
go run go2mermaid.go --func=formatNode

# 自動分析: other 模組中的 formatEdge 功能
go run go2mermaid.go --func=formatEdge

# 自動分析: other 模組中的 sanitizeText 功能
go run go2mermaid.go --func=sanitizeText

# 自動分析: other 模組中的 sanitizeID 功能
go run go2mermaid.go --func=sanitizeID

# 自動分析: other 模組中的 processFile 功能
go run go2mermaid.go --func=processFile

# 自動分析: other 模組中的 main 功能
go run go2mermaid.go --func=main

# 自動分析: other 模組中的 GetPathsConfig 功能
go run paths_config.go --func=GetPathsConfig

# 自動分析: other 模組中的 PathsConfig.EnsureDirectories 功能
go run paths_config.go --func=PathsConfig.EnsureDirectories

# 自動分析: other 模組中的 PathsConfig.GetAnalysisOutputDir 功能
go run paths_config.go --func=PathsConfig.GetAnalysisOutputDir

# 自動分析: other 模組中的 PathsConfig.GetDefaultOutputDir 功能
go run paths_config.go --func=PathsConfig.GetDefaultOutputDir


## Category: REPORTING
# 自動分析: reporting 模組中的 Stitcher.GenerateSystemFlow 功能
go run go2mermaid.go --func=Stitcher.GenerateSystemFlow

# 自動分析: reporting 模組中的 GenerateCLI 功能
go run go2mermaid.go --func=GenerateCLI


