"""
AIVA Common - 通用模組

這個包包含了 AIVA 系統中所有服務共享的通用組件，
包括數據結構定義、配置管理和工具函數。

符合官方標準:
- CVSS v3.1: Common Vulnerability Scoring System
- MITRE ATT&CK: 攻擊技術框架
- SARIF v2.1.0: Static Analysis Results Interchange Format
- CVE/CWE/CAPEC: 漏洞和弱點標識標準
"""

__version__ = "1.0.0"

# 從各模組中導出核心類別和枚舉
import contextlib

# 導入新增的通用模組
from . import enums, utils, schemas as common_schemas

from .enums import (
    AccessDecision,
    AssetExposure,
    AssetType,
    AttackPathEdgeType,
    AttackPathNodeType,
    BusinessCriticality,
    ComplianceFramework,
    Confidence,
    DataSensitivity,
    Environment,
    Exploitability,
    IntelSource,
    IOCType,
    Location,
    ModuleName,
    Permission,
    PersistenceType,
    PostExTestType,
    RemediationStatus,
    RemediationType,
    RiskLevel,
    ScanStatus,
    SensitiveInfoType,
    Severity,
    TaskStatus,
    TestStatus,
    ThreatLevel,
    Topic,
    VulnerabilityStatus,
    VulnerabilityType,
)

# 從 schemas.py 導入所有類（統一來源）
with contextlib.suppress(ImportError):
    # 授權分析; 安全標準和評分; 增強型漏洞處理; 功能任務相關; 核心消息系統
    # 模組狀態; OAST (Out-of-Band Application Security Testing); 後滲透測試
    # 修復建議; SARIF 報告格式; 掃描相關; 任務管理和遙測; 威脅情報; 漏洞和發現
    from .schemas import (
        AivaMessage,
        Asset,
        Authentication,
        AuthZAnalysisPayload,
        AuthZCheckPayload,
        AuthZResultPayload,
        CAPECReference,
        ConfigUpdatePayload,
        CVEReference,
        CVSSv3Metrics,
        CWEReference,
        EnhancedFindingPayload,
        EnhancedVulnerability,
        ExecutionError,
        FeedbackEventPayload,
        FindingEvidence,
        FindingImpact,
        FindingPayload,
        FindingRecommendation,
        Fingerprints,
        FunctionExecutionResult,
        FunctionTaskContext,
        FunctionTaskPayload,
        FunctionTaskTarget,
        FunctionTaskTestConfig,
        FunctionTelemetry,
        HeartbeatPayload,
        JavaScriptAnalysisResult,
        MessageHeader,
        ModuleStatus,
        OastEvent,
        OastProbe,
        PostExResultPayload,
        PostExTestPayload,
        RateLimit,
        RemediationGeneratePayload,
        RemediationResultPayload,
        SARIFLocation,
        SARIFReport,
        SARIFResult,
        SARIFRule,
        SARIFRun,
        SARIFTool,
        ScanCompletedPayload,
        ScanScope,
        ScanStartPayload,
        SensitiveMatch,
        Summary,
        Target,
        TaskUpdatePayload,
        ThreatIntelLookupPayload,
        ThreatIntelResultPayload,
        Vulnerability,
    )

# 只包含修復版本中實際存在且可以導入的項目
__all__ = [
    # Enums - 所有從 enums.py 導入的枚舉
    "ModuleName",
    "Topic",
    "Severity",
    "Confidence",
    "VulnerabilityType",
    "TaskStatus",
    "TestStatus",
    "ScanStatus",
    "SensitiveInfoType",
    "Location",
    "ThreatLevel",
    "IntelSource",
    "IOCType",
    "RemediationType",
    "RemediationStatus",
    "Permission",
    "AccessDecision",
    "PostExTestType",
    "PersistenceType",
    "BusinessCriticality",
    "Environment",
    "AssetType",
    "AssetExposure",
    "VulnerabilityStatus",
    "DataSensitivity",
    "Exploitability",
    "ComplianceFramework",
    "RiskLevel",
    "AttackPathNodeType",
    "AttackPathEdgeType",
    # Schemas - 從修復版本中導入的類
    "MessageHeader",
    "AivaMessage",
    "Authentication",
    "RateLimit",
    "ScanScope",
    "ScanStartPayload",
    "Asset",
    "Summary",
    "Fingerprints",
    "ScanCompletedPayload",
    "FunctionTaskTarget",
    "FunctionTaskContext",
    "FunctionTaskTestConfig",
    "FunctionTaskPayload",
    "FeedbackEventPayload",
    "Vulnerability",
    "Target",
    "FindingEvidence",
    "FindingImpact",
    "FindingRecommendation",
    "FindingPayload",
    "TaskUpdatePayload",
    "HeartbeatPayload",
    "ConfigUpdatePayload",
    "FunctionTelemetry",
    "ExecutionError",
    "FunctionExecutionResult",
    "OastEvent",
    "OastProbe",
    "ModuleStatus",
    "ThreatIntelLookupPayload",
    "ThreatIntelResultPayload",
    "AuthZCheckPayload",
    "AuthZAnalysisPayload",
    "AuthZResultPayload",
    "RemediationGeneratePayload",
    "RemediationResultPayload",
    "PostExTestPayload",
    "PostExResultPayload",
    "SensitiveMatch",
    "JavaScriptAnalysisResult",
    "CVSSv3Metrics",
    "CVEReference",
    "CWEReference",
    "CAPECReference",
    "SARIFLocation",
    "SARIFResult",
    "SARIFRule",
    "SARIFTool",
    "SARIFRun",
    "SARIFReport",
    "EnhancedVulnerability",
    "EnhancedFindingPayload",
]
