"""
AIVA Common Schemas - 向後兼容層

此文件重新導出所有已遷移到各模組 models.py 的類別。
⚠️ 此文件將逐步棄用，新代碼請直接從各模組的 models.py 導入。

遷移狀態:
- ✅ 基礎設施類 → aiva_common.models
- ✅ 掃描相關類 → scan.models
- ✅ 功能測試類 → function.models
- ✅ 集成相關類 → integration.models
- ✅ 核心業務類 → core.models
- ✅ AI 系統類 → core.ai_models
"""

# 從 aiva_common.models 重新導出基礎設施
# Pydantic BaseModel 重新導出
from pydantic import BaseModel

# 從 core.ai_models 重新導出 AI 系統
from services.core.ai_models import (
    AIExperienceCreatedEvent,
    AIModelDeployCommand,
    AIModelUpdatedEvent,
    AITraceCompletedEvent,
    AITrainingCompletedPayload,
    AITrainingProgressPayload,
    AITrainingStartPayload,
    AIVACommand,
    AIVAEvent,
    AIVARequest,
    AIVAResponse,
    AIVerificationRequest,
    AIVerificationResult,
    AttackPlan,
    AttackStep,
    ExperienceSample,
    ModelTrainingConfig,
    ModelTrainingResult,
    PlanExecutionMetrics,
    PlanExecutionResult,
    RAGKnowledgeUpdatePayload,
    RAGQueryPayload,
    RAGResponsePayload,
    ScenarioTestResult,
    SessionState,
    StandardScenario,
    TraceRecord,
)

# 從 core.models 重新導出核心業務
from services.core.models import (
    AttackPathEdge,
    AttackPathNode,
    AttackPathPayload,
    AttackPathRecommendation,
    CodeLevelRootCause,
    ConfigUpdatePayload,
    EnhancedAttackPath,
    EnhancedAttackPathNode,
    EnhancedFindingPayload,
    EnhancedModuleStatus,
    EnhancedRiskAssessment,
    EnhancedTaskExecution,
    EnhancedVulnerability,
    EnhancedVulnerabilityCorrelation,
    FeedbackEventPayload,
    FindingEvidence,
    FindingImpact,
    FindingPayload,
    FindingRecommendation,
    HeartbeatPayload,
    ModuleStatus,
    RemediationGeneratePayload,
    RemediationResultPayload,
    RiskAssessmentContext,
    RiskAssessmentResult,
    RiskFactor,
    RiskTrendAnalysis,
    SASTDASTCorrelation,
    SystemOrchestration,
    Target,
    TaskDependency,
    TaskQueue,
    TaskUpdatePayload,
    TestStrategy,
    VulnerabilityCorrelation,
)

# 從 function.models 重新導出功能測試
from services.function.models import (
    APISecurityTestPayload,
    APITestResult,
    AuthZCheckPayload,
    AuthZTestResult,
    BizLogicFindingPayload,
    BizLogicTestPayload,
    ExploitPayload,
    ExploitResult,
    FunctionTaskPayload,
    OastDetectedEvent,
    OastEvent,
    OastProbe,
    PostExTestPayload,
    SensitiveDataTestPayload,
    SensitiveMatch,
    TestExecution,
    TestExecutionDetail,
)

# 從 integration.models 重新導出集成相關
from services.integration.models import (
    EnhancedIOCRecord,
    NotificationPayload,
    SIEMEvent,
    SIEMEventPayload,
    ThreatIntelLookupPayload,
    ThreatIntelResultPayload,
    WebhookPayload,
)

# 從 scan.models 重新導出掃描相關
from services.scan.models import (
    Asset,
    AssetInventoryItem,
    AssetLifecyclePayload,
    EASMAsset,
    Fingerprints,
    JavaScriptAnalysisResult,
    ScanScope,
    ScanStartPayload,
    TechnicalFingerprint,
    Vulnerability,
    VulnerabilityDiscovery,
)

from .models import (
    AivaMessage,
    Authentication,
    CAPECReference,
    CVEReference,
    CVSSv3Metrics,
    CWEReference,
    MessageHeader,
    RateLimit,
    SARIFLocation,
    SARIFRegion,
    SARIFReport,
    SARIFResult,
    SARIFRun,
    TokenInfo,
    UserInfo,
)

__all__ = [
    # 基礎設施
    "AivaMessage",
    "Authentication",
    "BaseModel",
    "CAPECReference",
    "CVEReference",
    "CVSSv3Metrics",
    "CWEReference",
    "MessageHeader",
    "RateLimit",
    "SARIFLocation",
    "SARIFRegion",
    "SARIFReport",
    "SARIFResult",
    "SARIFRun",
    "TokenInfo",
    "UserInfo",
    # 掃描相關
    "Asset",
    "AssetInventoryItem",
    "AssetLifecyclePayload",
    "EASMAsset",
    "Fingerprints",
    "JavaScriptAnalysisResult",
    "ScanScope",
    "ScanStartPayload",
    "TechnicalFingerprint",
    "Vulnerability",
    "VulnerabilityDiscovery",
    # 功能測試
    "APISecurityTestPayload",
    "APITestResult",
    "AuthZCheckPayload",
    "AuthZTestResult",
    "BizLogicFindingPayload",
    "BizLogicTestPayload",
    "ExploitPayload",
    "ExploitResult",
    "FunctionTaskPayload",
    "OastDetectedEvent",
    "OastEvent",
    "OastProbe",
    "PostExTestPayload",
    "SensitiveDataTestPayload",
    "SensitiveMatch",
    "TestExecution",
    "TestExecutionDetail",
    # 集成相關
    "EnhancedIOCRecord",
    "NotificationPayload",
    "SIEMEvent",
    "SIEMEventPayload",
    "ThreatIntelLookupPayload",
    "ThreatIntelResultPayload",
    "WebhookPayload",
    # 核心業務
    "AttackPathEdge",
    "AttackPathNode",
    "AttackPathPayload",
    "AttackPathRecommendation",
    "CodeLevelRootCause",
    "ConfigUpdatePayload",
    "EnhancedAttackPath",
    "EnhancedAttackPathNode",
    "EnhancedFindingPayload",
    "EnhancedModuleStatus",
    "EnhancedRiskAssessment",
    "EnhancedTaskExecution",
    "EnhancedVulnerability",
    "EnhancedVulnerabilityCorrelation",
    "FeedbackEventPayload",
    "FindingEvidence",
    "FindingImpact",
    "FindingPayload",
    "FindingRecommendation",
    "HeartbeatPayload",
    "ModuleStatus",
    "RemediationGeneratePayload",
    "RemediationResultPayload",
    "RiskAssessmentContext",
    "RiskAssessmentResult",
    "RiskFactor",
    "RiskTrendAnalysis",
    "SASTDASTCorrelation",
    "SystemOrchestration",
    "Target",
    "TaskDependency",
    "TaskQueue",
    "TaskUpdatePayload",
    "TestStrategy",
    "VulnerabilityCorrelation",
    # AI 系統
    "AIExperienceCreatedEvent",
    "AIModelDeployCommand",
    "AIModelUpdatedEvent",
    "AITraceCompletedEvent",
    "AITrainingCompletedPayload",
    "AITrainingProgressPayload",
    "AITrainingStartPayload",
    "AIVACommand",
    "AIVAEvent",
    "AIVARequest",
    "AIVAResponse",
    "AIVerificationRequest",
    "AIVerificationResult",
    "AttackPlan",
    "AttackStep",
    "ExperienceSample",
    "ModelTrainingConfig",
    "ModelTrainingResult",
    "PlanExecutionMetrics",
    "PlanExecutionResult",
    "RAGKnowledgeUpdatePayload",
    "RAGQueryPayload",
    "RAGResponsePayload",
    "ScenarioTestResult",
    "SessionState",
    "StandardScenario",
    "TraceRecord",
]
