# AIVA Go Analysis CLI Commands
# Auto-generated by go2mermaid

## Category: ANALYSIS
# [PLACEHOLDER] VulnDatabase.parseRetireJS 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.parseRetireJS

# [PLACEHOLDER] VulnDatabase.parseNVD 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.parseNVD

# [PLACEHOLDER] VulnDatabase.parseSnyk 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.parseSnyk

# [PLACEHOLDER] VulnDatabase.parseGHSA 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.parseGHSA

# [PLACEHOLDER] analyzeFuncDecl 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\tools\analyze_call_chain.go --func=analyzeFuncDecl

# [PLACEHOLDER] analyzeCondition 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\tools\analyze_call_chain.go --func=analyzeCondition


## Category: OTHER
# [PLACEHOLDER] main 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\cspm-scanner\main.go --func=main

# [PLACEHOLDER] main 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\sca-scanner\main.go --func=main

# [PLACEHOLDER] getSSRFPayloads 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=getSSRFPayloads

# [PLACEHOLDER] containsSensitiveContent 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=containsSensitiveContent

# [PLACEHOLDER] extractParams 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=extractParams

# [PLACEHOLDER] setHeaders 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=setHeaders

# [PLACEHOLDER] truncateString 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=truncateString

# [PLACEHOLDER] main 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=main

# [PLACEHOLDER] outputResult 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=outputResult

# [PLACEHOLDER] outputError 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=outputError

# [PLACEHOLDER] NewWorkerPool 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\common\worker_pool.go --func=NewWorkerPool

# [PLACEHOLDER] WorkerPool.worker 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\common\worker_pool.go --func=WorkerPool.worker

# [PLACEHOLDER] WorkerPool.Submit 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\common\worker_pool.go --func=WorkerPool.Submit

# [PLACEHOLDER] WorkerPool.Results 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\common\worker_pool.go --func=WorkerPool.Results

# [PLACEHOLDER] WorkerPool.Close 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\common\worker_pool.go --func=WorkerPool.Close

# [PLACEHOLDER] WorkerPool.Shutdown 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\common\worker_pool.go --func=WorkerPool.Shutdown

# [PLACEHOLDER] NewAWSAuditor 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=NewAWSAuditor

# [PLACEHOLDER] AWSAuditor.AuditS3Buckets 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=AWSAuditor.AuditS3Buckets

# [PLACEHOLDER] isPublicACL 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=isPublicACL

# [PLACEHOLDER] AWSAuditor.AuditIAMUsers 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=AWSAuditor.AuditIAMUsers

# [PLACEHOLDER] AWSAuditor.AuditSecurityGroups 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=AWSAuditor.AuditSecurityGroups

# [PLACEHOLDER] AWSAuditor.AuditCloudTrail 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=AWSAuditor.AuditCloudTrail

# [PLACEHOLDER] AWSAuditor.AuditKMSKeys 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=AWSAuditor.AuditKMSKeys

# [PLACEHOLDER] AWSAuditor.RunFullAudit 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\audit\aws.go --func=AWSAuditor.RunFullAudit

# [PLACEHOLDER] stringPtr 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=stringPtr

# [PLACEHOLDER] mapSeverity 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=mapSeverity

# [PLACEHOLDER] copyParams 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=copyParams

# [PLACEHOLDER] NewParameterFuzzer 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=NewParameterFuzzer

# [PLACEHOLDER] loadPayloads 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=loadPayloads

# [PLACEHOLDER] ParameterFuzzer.measureResponseTime 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=ParameterFuzzer.measureResponseTime

# [PLACEHOLDER] ParameterFuzzer.makeRequest 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=ParameterFuzzer.makeRequest

# [PLACEHOLDER] copyParams 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=copyParams

# [PLACEHOLDER] readBody 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=readBody

# [PLACEHOLDER] NewVulnDatabase 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=NewVulnDatabase

# [PLACEHOLDER] VulnDatabase.LoadFromFiles 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.LoadFromFiles

# [PLACEHOLDER] VulnDatabase.loadSource 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.loadSource

# [PLACEHOLDER] VulnDatabase.CheckVersion 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.CheckVersion

# [PLACEHOLDER] VulnDatabase.CheckPackageJSON 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.CheckPackageJSON

# [PLACEHOLDER] VulnDatabase.CheckRequirementsTxt 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.CheckRequirementsTxt

# [PLACEHOLDER] isVersionAffected 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=isVersionAffected

# [PLACEHOLDER] deduplicateCVEs 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=deduplicateCVEs

# [PLACEHOLDER] cleanVersion 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=cleanVersion

# [PLACEHOLDER] VulnDatabase.GetStats 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\sca\database\vuln_database.go --func=VulnDatabase.GetStats

# [PLACEHOLDER] NewInternalServiceProbe 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\internal_microservice_probe.go --func=NewInternalServiceProbe

# [PLACEHOLDER] InternalServiceProbe.ProbeTarget 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\internal_microservice_probe.go --func=InternalServiceProbe.ProbeTarget

# [PLACEHOLDER] InternalServiceProbe.ProbeCommonPorts 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\internal_microservice_probe.go --func=InternalServiceProbe.ProbeCommonPorts

# [PLACEHOLDER] main 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\tools\analyze_call_chain.go --func=main

# [PLACEHOLDER] exprToString 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\tools\analyze_call_chain.go --func=exprToString

# [PLACEHOLDER] hasReturn 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\tools\analyze_call_chain.go --func=hasReturn

# [PLACEHOLDER] printAnalysis 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\tools\analyze_call_chain.go --func=printAnalysis


## Category: RECONNAISSANCE
# [PLACEHOLDER] NewSSRFScanner 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=NewSSRFScanner

# [PLACEHOLDER] SSRFScanner.Scan 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.Scan

# [PLACEHOLDER] SSRFScanner.getBaseline 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.getBaseline

# [PLACEHOLDER] SSRFScanner.testPayload 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.testPayload

# [PLACEHOLDER] SSRFScanner.analyzeResponse 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\cmd\ssrf-scanner\main.go --func=SSRFScanner.analyzeResponse

# [PLACEHOLDER] NewCSPMScanner 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=NewCSPMScanner

# [PLACEHOLDER] CSPMScanner.Scan 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.Scan

# [PLACEHOLDER] CSPMScanner.scanAWS 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.scanAWS

# [PLACEHOLDER] CSPMScanner.scanAzure 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.scanAzure

# [PLACEHOLDER] CSPMScanner.scanGCP 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.scanGCP

# [PLACEHOLDER] CSPMScanner.scanKubernetes 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.scanKubernetes

# [PLACEHOLDER] CSPMScanner.scanGeneric 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.scanGeneric

# [PLACEHOLDER] CSPMScanner.scanWithTrivy 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.scanWithTrivy

# [PLACEHOLDER] CSPMScanner.parseTrivyOutput 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.parseTrivyOutput

# [PLACEHOLDER] CSPMScanner.createFinding 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\cspm\scanner\cspm_scanner.go --func=CSPMScanner.createFinding

# [PLACEHOLDER] NewOpenRedirectDetector 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=NewOpenRedirectDetector

# [PLACEHOLDER] OpenRedirectDetector.Test 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=OpenRedirectDetector.Test

# [PLACEHOLDER] OpenRedirectDetector.TestWithReferrer 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=OpenRedirectDetector.TestWithReferrer

# [PLACEHOLDER] OpenRedirectDetector.TestCommonParams 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=OpenRedirectDetector.TestCommonParams

# [PLACEHOLDER] OpenRedirectDetector.isRedirect 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=OpenRedirectDetector.isRedirect

# [PLACEHOLDER] OpenRedirectDetector.isMaliciousRedirect 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=OpenRedirectDetector.isMaliciousRedirect

# [PLACEHOLDER] OpenRedirectDetector.makeRequest 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\detectors\open_redirect.go --func=OpenRedirectDetector.makeRequest

# [PLACEHOLDER] ParameterFuzzer.DetectSQLInjection 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=ParameterFuzzer.DetectSQLInjection

# [PLACEHOLDER] ParameterFuzzer.DetectCommandInjection 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=ParameterFuzzer.DetectCommandInjection

# [PLACEHOLDER] ParameterFuzzer.DetectSSTI 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=ParameterFuzzer.DetectSSTI

# [PLACEHOLDER] ParameterFuzzer.DetectAll 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\fuzzer\parameter_fuzzer.go --func=ParameterFuzzer.DetectAll

# [PLACEHOLDER] NewCloudMetadataScanner 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\cloud_metadata_scanner.go --func=NewCloudMetadataScanner

# [PLACEHOLDER] CloudMetadataScanner.ScanForMetadata 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\cloud_metadata_scanner.go --func=CloudMetadataScanner.ScanForMetadata

# [PLACEHOLDER] CloudMetadataScanner.probeEndpoint 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\cloud_metadata_scanner.go --func=CloudMetadataScanner.probeEndpoint

# [PLACEHOLDER] CloudMetadataScanner.fetchAwsV2Token 功能
go run C:\D\fold7\AIVA-git\services\scan\go_engine\internal\ssrf\detector\cloud_metadata_scanner.go --func=CloudMetadataScanner.fetchAwsV2Token


