capability_evaluator:
  batch_size: 100
  benchmark_cache_enabled: true
  benchmark_timeout_seconds: 10.0
  cache_strategy: hybrid
  cache_ttl_seconds: 3600
  connection_pool_size: 20
  connection_pool_timeout: 5.0
  enable_performance_monitoring: true
  evaluation_cache_enabled: true
  evidence_batch_processing: true
  lightweight_monitoring: true
  max_cache_size: 5000
  max_concurrent_operations: 16
  max_evaluation_workers: 8
  metrics_sampling_rate: 0.01
  monitoring_batch_size: 50
  monitoring_interval_seconds: 60.0
  operation_timeout_seconds: 30.0
  parallel_evaluation_enabled: true
  skip_redundant_benchmarks: true
experience_manager:
  async_storage_enabled: true
  auto_cleanup_enabled: true
  batch_insert_enabled: true
  batch_size: 500
  cache_strategy: hybrid
  cache_ttl_seconds: 7200
  cleanup_interval_hours: 24
  compression_enabled: true
  connection_pool_size: 50
  connection_pool_timeout: 5.0
  enable_performance_monitoring: true
  index_optimization_enabled: true
  max_cache_size: 10000
  max_concurrent_operations: 20
  max_query_results: 1000
  metrics_sampling_rate: 0.01
  operation_timeout_seconds: 30.0
  query_planning_enabled: true
  query_result_cache_enabled: true
  retention_policy_days: 30
  session_cache_size: 100
  session_pooling_enabled: true
  session_timeout_minutes: 30
  storage_backend: postgresql
  storage_buffer_size: 1000
