capability_evaluator:
  batch_size: 100
  benchmark_cache_enabled: true
  benchmark_timeout_seconds: 10.0
  cache_strategy: memory_only
  cache_ttl_seconds: 300
  connection_pool_size: 20
  connection_pool_timeout: 5.0
  enable_performance_monitoring: false
  evaluation_cache_enabled: true
  evidence_batch_processing: true
  lightweight_monitoring: true
  max_cache_size: 100
  max_concurrent_operations: 2
  max_evaluation_workers: 2
  metrics_sampling_rate: 0.1
  monitoring_batch_size: 50
  monitoring_interval_seconds: 300.0
  operation_timeout_seconds: 30.0
  parallel_evaluation_enabled: true
  skip_redundant_benchmarks: true
experience_manager:
  async_storage_enabled: true
  auto_cleanup_enabled: true
  batch_insert_enabled: true
  batch_size: 50
  cache_strategy: memory_only
  cache_ttl_seconds: 600
  cleanup_interval_hours: 24
  compression_enabled: true
  connection_pool_size: 20
  connection_pool_timeout: 5.0
  enable_performance_monitoring: false
  index_optimization_enabled: true
  max_cache_size: 500
  max_concurrent_operations: 4
  max_query_results: 1000
  metrics_sampling_rate: 0.1
  operation_timeout_seconds: 30.0
  query_planning_enabled: true
  query_result_cache_enabled: true
  retention_policy_days: 30
  session_cache_size: 100
  session_pooling_enabled: true
  session_timeout_minutes: 30
  storage_backend: memory
  storage_buffer_size: 1000
