batch_size: 50
benchmark_cache_enabled: true
benchmark_timeout_seconds: 8.0
cache_strategy: hybrid
cache_ttl_seconds: 1800
connection_pool_size: 20
connection_pool_timeout: 5.0
enable_performance_monitoring: true
evaluation_cache_enabled: true
evidence_batch_processing: true
lightweight_monitoring: true
max_cache_size: 2000
max_concurrent_operations: 8
max_evaluation_workers: 6
metrics_sampling_rate: 0.05
monitoring_batch_size: 100
monitoring_interval_seconds: 120.0
operation_timeout_seconds: 15.0
parallel_evaluation_enabled: true
skip_redundant_benchmarks: true
