async_storage_enabled: true
auto_cleanup_enabled: true
batch_insert_enabled: true
batch_size: 200
cache_strategy: hybrid
cache_ttl_seconds: 7200
cleanup_interval_hours: 12
compression_enabled: true
connection_pool_size: 30
connection_pool_timeout: 3.0
enable_performance_monitoring: true
index_optimization_enabled: true
max_cache_size: 5000
max_concurrent_operations: 12
max_query_results: 500
metrics_sampling_rate: 0.02
operation_timeout_seconds: 20.0
query_planning_enabled: true
query_result_cache_enabled: true
retention_policy_days: 60
session_cache_size: 200
session_pooling_enabled: true
session_timeout_minutes: 60
storage_backend: hybrid
storage_buffer_size: 2000
