flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        新增警報\n\n        Args:\n           ...]
    n4[alert = &#123;&amp;&#35;39;timestamp&amp;&#35;39;: dateti...]
    n5[self._alerts.append&#40;alert&#41;]
    n6{if len&#40;self._alerts&#41; &amp;gt; 1000}
    n7[self._alerts = self._alerts&#91;-1000:&#93;]
    n8[]
    n9[logger.warning&#40;f&amp;&#35;39;Alert &#91;&#123;level.u...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 -->|Yes| n7
    n6 -->|No| n8
    n7 --> n8
    n8 --> n9
    n9 --> n2