flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;驗證埠號.&amp;&#35;39;]
    n4{if not 1024 &amp;lt;= v &amp;lt;= 65535}
    n5[raise ValueError&#40;&amp;&#35;39;Port must be between 10...]
    n6[]
    n7[return v]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n2