flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        獲取掃描進度\n\n        Args:\n         ...]
    n4[stats = self._scan_stats&#91;sca...]
    n5[total = stats&#91;&amp;&#35;39;total&amp;&#35;39;&#93;]
    n6[completed = stats&#91;&amp;&#35;39;completed&amp;&#35;39;...]
    n7[failed = stats&#91;&amp;&#35;39;failed&amp;&#35;39;&#93;]
    n8[return &#123;&amp;&#35;39;scan_id&amp;&#35;39;: scan_id, ...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2