flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;Wrap function payload into AIVA message with...]
    n4[return AivaMessage&#40;header=MessageHead...]
    n1 --> n3
    n3 --> n4
    n4 --> n2