flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        記錄任務完成\n\n        Args:\n         ...]
    n4{if task_id not in self._task_m...}
    n5[return]
    n6[]
    n7[task_metric = self._task_metrics&#91;t...]
    n8[end_time = datetime.now&#40;UTC&#41;]
    n9{if not duration_seconds}
    n10[duration_seconds = &#40;end_time - task_met...]
    n11[]
    n12[task_metric.update&#40;&#123;&amp;&#35;39;end_time&amp;&#...]
    n13[self._system_metrics&#91;&amp;&#35;39;total_tasks_process...]
    n14{if not success}
    n15[self._system_metrics&#91;&amp;&#35;39;failed_tasks&amp;&#...]
    n16[]
    n17[total_tasks = self._system_metrics...]
    n18[old_avg = self._system_metrics...]
    n19[self._system_metrics&#91;&amp;&#35;39;avg_task_duration&a...]
    n20[status_text = &amp;&#35;39;success&amp;&#35;39; if succes...]
    n21[logger.info&#40;f&amp;&#35;39;Task &#123;task_id&#125; co...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n11
    n11 --> n12
    n12 --> n13
    n13 --> n14
    n14 -->|Yes| n15
    n14 -->|No| n16
    n15 --> n16
    n16 --> n17
    n17 --> n18
    n18 --> n19
    n19 --> n20
    n20 --> n21
    n21 --> n2