flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;驗證目標.&amp;&#35;39;]
    n4{if not v.strip&#40;&#41;}
    n5[raise ValueError&#40;&amp;&#35;39;Target cannot be empty&...]
    n6[]
    n7[return v.strip&#40;&#41;]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n2