flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        記錄任務開始執行\n\n        Args:\n       ...]
    n4[self._task_metrics&#91;task_id&#93; = &#123;&amp;&#35;39;...]
    n5[logger.info&#40;f&amp;&#35;39;Task &#123;task_id&#125; st...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2