flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;記錄測試的協議&amp;&#35;39;]
    n4{if protocol not in self.protoc...}
    n5[self.protocols_tested.append&#40;protocol&#41;]
    n6[]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n2