flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;記錄引擎執行&amp;&#35;39;]
    n4{if engine_name not in self.eng...}
    n5[self.engines_run.append&#40;engine_name&#41;]
    n6[]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n2