flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        Determine whether the supplied res...]
    n4{if not response}
    n5[return False]
    n6[]
    n7[success_indicators = &#91;&amp;&#35;39;&amp;lt;html&amp;&...]
    n8[response_lower = response.lower&#40;&#41;]
    n9[return any&#40;&#40;indicator in response_low...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n2