flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;檢查UNION查詢是否成功&amp;&#35;39;]
    n4[content_lower = content.lower&#40;&#41;]
    n5{for pattern in self.union_indica...}
    n6{if re.search&#40;pattern, content_...}
    n7[return True]
    n8[]
    n9[]
    n10[return False]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n9
    n6 -->|Yes| n7
    n6 -->|No| n8
    n7 --> n8
    n8 --> n5
    n9 --> n10
    n10 --> n2