flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;構建水平 IDOR 檢測結果&amp;&#35;39;]
    n4[from services.aiva_common.enums import Confidence,...]
    n5[from services.aiva_common.schemas import FindingEv...]
    n6[from services.aiva_common.utils import new_id]
    n7[return &#123;&amp;&#35;39;finding_id&amp;&#35;39;: new_id...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n2