flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;檢查欄位數量錯誤（表示UNION語法有效）&amp;&#35;39;]
    n4{for pattern in self.column_count...}
    n5{if re.search&#40;pattern, content,...}
    n6[return True]
    n7[]
    n8[]
    n9[return False]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n8
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n7
    n7 --> n4
    n8 --> n9
    n9 --> n2