flowchart TB
    n1([開始])
    n2([結束])
    n3[prefix = f&amp;&#35;39;&#91;&#123;self.vector&#125;&#93;&...]
    n4[return f&amp;&#35;39;&#123;prefix&#125; &#123;self.payloa...]
    n1 --> n3
    n3 --> n4
    n4 --> n2