flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        優先級排序測試向量\n\n        Args:\n      ...]
    n4{if not self.config.cloud_metad...}
    n5[return vectors]
    n6[]
    n7[cloud_vectors = &#91;&#93;]
    n8[other_vectors = &#91;&#93;]
    n9{for vector in vectors}
    n10[payload = str&#40;vector.payload&#41;....]
    n11[is_cloud = any&#40;&#40;endpoint in pay...]
    n12{if is_cloud}
    n13[cloud_vectors.append&#40;vector&#41;]
    n14[other_vectors.append&#40;vector&#41;]
    n15[]
    n16[]
    n17[logger.debug&#40;f&amp;&#35;39;Vector prioritization: &#1...]
    n18[return cloud_vectors + other_vectors]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n16
    n10 --> n11
    n11 --> n12
    n12 -->|Yes| n13
    n12 -->|No| n14
    n13 --> n15
    n14 --> n15
    n15 --> n9
    n16 --> n17
    n17 --> n18
    n18 --> n2