flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        判斷是否存在 BFLA 漏洞\n\n        漏洞條件：\n ...]
    n4[admin_success = 200 &amp;lt;= admin_respons...]
    n5[user_success = 200 &amp;lt;= user_response...]
    n6{if admin_success and user_success}
    n7[return True]
    n8[]
    n9[return admin_success and user_respons...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 -->|Yes| n7
    n6 -->|No| n8
    n7 --> n8
    n8 --> n9
    n9 --> n2