flowchart TB
    n1([開始])
    n2([結束])
    n3[self._db_patterns = &#123;&amp;&#35;39;MySQL&amp;&#35;39;...]
    n4[self._version_patterns = &#123;&amp;&#35;39;MySQL&amp;&#3...]
    n1 --> n3
    n3 --> n4
    n4 --> n2