flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;設置預設檢測引擎&amp;&#35;39;]
    n4{if self.config.enable_error_de...}
    n5[self.register_engine&#40;&amp;&#35;39;error&amp;&#35;39;,...]
    n6[]
    n7{if self.config.enable_boolean_...}
    n8[self.register_engine&#40;&amp;&#35;39;boolean&amp;&#35;39...]
    n9[]
    n10{if self.config.enable_time_det...}
    n11[self.register_engine&#40;&amp;&#35;39;time&amp;&#35;39;, ...]
    n12[]
    n13{if self.config.enable_union_de...}
    n14[self.register_engine&#40;&amp;&#35;39;union&amp;&#35;39;,...]
    n15[]
    n16{if self.config.enable_oob_dete...}
    n17[self.register_engine&#40;&amp;&#35;39;oob&amp;&#35;39;, O...]
    n18[]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 -->|Yes| n8
    n7 -->|No| n9
    n8 --> n9
    n9 --> n10
    n10 -->|Yes| n11
    n10 -->|No| n12
    n11 --> n12
    n12 --> n13
    n13 -->|Yes| n14
    n13 -->|No| n15
    n14 --> n15
    n15 --> n16
    n16 -->|Yes| n17
    n16 -->|No| n18
    n17 --> n18
    n18 --> n2