flowchart TB
    n1([開始])
    n2([結束])
    n3{if not mapping}
    n4[return &#123;parameter or &amp;&#35;39;xss_probe&amp;&#35...]
    n5[]
    n6{if parameter and parameter in ...}
    n7[mapping&#91;parameter&#93; = payload]
    n8[return mapping]
    n9[]
    n10{if parameter and parameter not...}
    n11[mapping&#91;parameter&#93; = payload]
    n12[return mapping]
    n13[]
    n14{for key in list&#40;mapping.keys&#40;&#41;&#41;}
    n15[mapping&#91;key&#93; = payload]
    n16[]
    n17[return mapping]
    n1 --> n3
    n3 -->|Yes| n4
    n3 -->|No| n5
    n4 --> n5
    n5 --> n6
    n6 -->|Yes| n7
    n6 -->|No| n9
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 -->|Yes| n11
    n10 -->|No| n13
    n11 --> n12
    n12 --> n13
    n13 --> n14
    n14 -->|Yes| n15
    n14 -->|No| n16
    n15 --> n14
    n16 --> n17
    n17 --> n2