flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;索引單個檔案.\n\n        Args:\n            file_p...]
    n4[try]
    n5[tree = ast.parse&#40;content&#41;]
    n6{for node in ast.walk&#40;tree&#41;}
    n7{if isinstance&#40;node, ast.Functi...}
    n8[chunk_content = ast.get_source_segme...]
    n9{if chunk_content}
    n10[self._add_chunk&#40;file_path=str&#40;file_path.relative_...]
    n11[]
    n12[]
    n13[]
    n14[]
    n15[except SyntaxError]
    n16[self._add_chunk&#40;file_path=str&#40;file_path.relative_...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n4 --> n15
    n5 --> n6
    n6 -->|Yes| n7
    n6 -->|No| n13
    n7 -->|Yes| n8
    n7 -->|No| n12
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n11
    n11 --> n12
    n12 --> n6
    n13 --> n14
    n14 --> n2
    n15 --> n16
    n16 --> n14