flowchart TB
    n1([開始])
    n2([結束])
    n3[details: dict&#91;str, Any&#93; = &#123;&amp;&#35;39;atte...]
    n4{if self.errors}
    n5[details&#91;&amp;&#35;39;errors&amp;&#35;39;&#93; = self....]
    n6[]
    n7[return details]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n2