flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;匯出為 XML 格式&amp;&#35;39;]
    n4[xml_lines = &#91;&amp;&#35;39;&amp;lt;?xml version=&amp;q...]
    n5[xml_lines.append&#40;&amp;&#35;39;&amp;lt;SecurityReport&...]
    n6[xml_lines.extend&#40;self._dict_to_xml&#40;content, inden...]
    n7[xml_lines.append&#40;&amp;&#35;39;&amp;lt;/SecurityReport...]
    n8[return &amp;&#35;39;\n&amp;&#35;39;.join&#40;xml_lines&#41;]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2