flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;清空圖（危險操作,僅用於測試）&amp;&#35;39;]
    n4[with self.driv...]
    n5[session.run&#40;&amp;&#35;39;MATCH &#40;n&#41; DETACH DEL...]
    n6[logger.warning&#40;&amp;&#35;39;Graph cleared!&amp;&#35;3...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n2