flowchart TB
    n1([開始])
    n2([結束])
    n3[self._risk_matrix = &#123;&amp;&#35;39;critical&amp;&#35;...]
    n4[self._environment_multipliers = &#123;&amp;&#35;39;produc...]
    n1 --> n3
    n3 --> n4
    n4 --> n2