flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取客戶端 IP 地址&amp;&#35;39;]
    n4[forwarded_for = request.headers.get&#40;...]
    n5{if forwarded_for}
    n6[return forwarded_for.split&#40;&amp;&#35;39;,&amp;&#35;39...]
    n7[]
    n8[real_ip = request.headers.get&#40;...]
    n9{if real_ip}
    n10[return real_ip]
    n11[]
    n12[return request.client.host if request...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 -->|Yes| n6
    n5 -->|No| n7
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 -->|Yes| n10
    n9 -->|No| n11
    n10 --> n11
    n11 --> n12
    n12 --> n2