flowchart TB
    n1([開始])
    n2([結束])
    n3{if self.start_time is not None}
    n4[self.duration = time.perf_counter&#40;&#41; ...]
    n5[]
    n1 --> n3
    n3 -->|Yes| n4
    n3 -->|No| n5
    n4 --> n5
    n5 --> n2