flowchart TB
    n1([開始])
    n2([結束])
    n3[self._correlation_rules = &#123;&amp;&#35;39;xss&amp;&#35...]
    n4[self._attack_chains = &#91;&#91;&amp;&#35;39;info_disclos...]
    n1 --> n3
    n3 --> n4
    n4 --> n2