flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        檢查主機名是否被允許（內部方法）\n\n        Args:\...]
    n4{if not hostname}
    n5[return False]
    n6[]
    n7{if not self._allowed_hosts_set}
    n8[return True]
    n9[]
    n10{if hostname in self._allowed_h...}
    n11[return True]
    n12[]
    n13{if self.scope.include_subdomains}
    n14{for allowed_host in self._allowed_hos...}
    n15{if hostname.endswith&#40;f&amp;&#35;39;.&#123;allow...}
    n16[return True]
    n17[]
    n18[]
    n19[]
    n20[return False]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 -->|Yes| n8
    n7 -->|No| n9
    n8 --> n9
    n9 --> n10
    n10 -->|Yes| n11
    n10 -->|No| n12
    n11 --> n12
    n12 --> n13
    n13 -->|Yes| n14
    n13 -->|No| n19
    n14 -->|Yes| n15
    n14 -->|No| n18
    n15 -->|Yes| n16
    n15 -->|No| n17
    n16 --> n17
    n17 --> n14
    n18 --> n19
    n19 --> n20
    n20 --> n2