flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        檢查 URL 是否匹配任何排除模式\n\n        Args:...]
    n4[return any&#40;&#40;pattern.search&#40;url&#41; for p...]
    n1 --> n3
    n3 --> n4
    n4 --> n2