flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        添加允許的主機\n\n        Args:\n        ...]
    n4{if hostname and hostname not i...}
    n5[self._allowed_hosts_set.add&#40;hostname&#41;]
    n6[self.scope.allowed_hosts.append&#40;hostname&#41;]
    n7[logger.info&#40;f&amp;&#35;39;Added allowed host: &#123;h...]
    n8[]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n8
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2