flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取成功率&amp;&#35;39;]
    n4{if not self._results}
    n5[return 0.0]
    n6[]
    n7[successful = sum&#40;&#40;1 for r in self...]
    n8[return successful / len&#40;self._results...]
    n1 --> n3
    n3 --> n4
    n4 -->|Yes| n5
    n4 -->|No| n6
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2