flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        克隆當前配置\n\n        Returns:\n      ...]
    n4[new_config = HeaderConfiguration&#40;...]
    n5[return new_config]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2