flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n掃描編排器 - 統一管理掃描流程的核心邏輯\n&amp;&#35;39;]
    n4[from __future__ import annotations]
    n5[from typing import TYPE_CHECKING]
    n6[from services.aiva_common.schemas import Asset, Sc...]
    n7[from services.aiva_common.utils import get_logger,...]
    n8[from .authentication_manager import Authentication...]
    n9[from .core_crawling_engine.http_client_hi import H...]
    n10[from .core_crawling_engine.static_content_parser i...]
    n11[from .core_crawling_engine.url_queue_manager impor...]
    n12[from .fingerprint_manager import FingerprintCollec...]
    n13[from .header_configuration import HeaderConfigurat...]
    n14{if TYPE_CHECKING}
    n15[from .scan_context import ScanContext]
    n16[]
    n17[logger = get_logger&#40;__name__&#41;]
    n18[class ScanOrchestrator&#40;...&#41;]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n9
    n9 --> n10
    n10 --> n11
    n11 --> n12
    n12 --> n13
    n13 --> n14
    n14 -->|Yes| n15
    n14 -->|No| n16
    n15 --> n16
    n16 --> n17
    n17 --> n18
    n18 --> n2