flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        獲取隨機 User-Agent\n\n        Returns...]
    n4[return random.choice&#40;self._DEFAULT_US...]
    n1 --> n3
    n3 --> n4
    n4 --> n2