# AIVA Go Analysis CLI Commands
# Auto-generated by go2mermaid

## Category: ANALYSIS
# [PLACEHOLDER] Stitcher.AnalyzeBranches 功能
go run go2mermaid.go --func=Stitcher.AnalyzeBranches


## Category: OTHER
# [PLACEHOLDER] NewStitcher 功能
go run go2mermaid.go --func=NewStitcher

# [PLACEHOLDER] Stitcher.AddScript 功能
go run go2mermaid.go --func=Stitcher.AddScript

# [PLACEHOLDER] Stitcher.ResolveConnections 功能
go run go2mermaid.go --func=Stitcher.ResolveConnections

# [PLACEHOLDER] Stitcher.findProviderInPackage 功能
go run go2mermaid.go --func=Stitcher.findProviderInPackage

# [PLACEHOLDER] NewClassifier 功能
go run go2mermaid.go --func=NewClassifier

# [PLACEHOLDER] Classifier.Classify 功能
go run go2mermaid.go --func=Classifier.Classify

# [PLACEHOLDER] Classifier.GetResult 功能
go run go2mermaid.go --func=Classifier.GetResult

# [PLACEHOLDER] NewBuilder 功能
go run go2mermaid.go --func=NewBuilder

# [PLACEHOLDER] Builder.BuildFunction 功能
go run go2mermaid.go --func=Builder.BuildFunction

# [PLACEHOLDER] Builder.buildStmt 功能
go run go2mermaid.go --func=Builder.buildStmt

# [PLACEHOLDER] Builder.inspectBlock 功能
go run go2mermaid.go --func=Builder.inspectBlock

# [PLACEHOLDER] Builder.inspectStmt 功能
go run go2mermaid.go --func=Builder.inspectStmt

# [PLACEHOLDER] Builder.inspectExpr 功能
go run go2mermaid.go --func=Builder.inspectExpr

# [PLACEHOLDER] getFunctionName 功能
go run go2mermaid.go --func=getFunctionName

# [PLACEHOLDER] NewGraph 功能
go run go2mermaid.go --func=NewGraph

# [PLACEHOLDER] Graph.Add 功能
go run go2mermaid.go --func=Graph.Add

# [PLACEHOLDER] Graph.Link 功能
go run go2mermaid.go --func=Graph.Link

# [PLACEHOLDER] Graph.ToMermaid 功能
go run go2mermaid.go --func=Graph.ToMermaid

# [PLACEHOLDER] formatNode 功能
go run go2mermaid.go --func=formatNode

# [PLACEHOLDER] formatEdge 功能
go run go2mermaid.go --func=formatEdge

# [PLACEHOLDER] sanitizeText 功能
go run go2mermaid.go --func=sanitizeText

# [PLACEHOLDER] sanitizeID 功能
go run go2mermaid.go --func=sanitizeID

# [PLACEHOLDER] processFile 功能
go run go2mermaid.go --func=processFile

# [PLACEHOLDER] main 功能
go run go2mermaid.go --func=main

# [PLACEHOLDER] GetPathsConfig 功能
go run paths_config.go --func=GetPathsConfig

# [PLACEHOLDER] PathsConfig.EnsureDirectories 功能
go run paths_config.go --func=PathsConfig.EnsureDirectories

# [PLACEHOLDER] PathsConfig.GetAnalysisOutputDir 功能
go run paths_config.go --func=PathsConfig.GetAnalysisOutputDir

# [PLACEHOLDER] PathsConfig.GetDefaultOutputDir 功能
go run paths_config.go --func=PathsConfig.GetDefaultOutputDir


## Category: REPORTING
# [PLACEHOLDER] Stitcher.GenerateSystemFlow 功能
go run go2mermaid.go --func=Stitcher.GenerateSystemFlow

# [PLACEHOLDER] GenerateCLI 功能
go run go2mermaid.go --func=GenerateCLI


