"""
AIVA Common Enums Package

此套件提供了 AIVA 微服務生態系統中所有枚舉類型的統一介面。

使用方式:
    from aiva_common.enums import ModuleName, Severity, VulnerabilityType

架構說明:
    - common.py: 通用枚舉 (狀態、級別等)
    - modules.py: 模組相關枚舉 (模組名稱、主題)
    - security.py: 安全測試枚舉 (漏洞、攻擊類型等)
    - assets.py: 資產管理枚舉 (資產類型、環境等)
"""

# ==================== 學術研究和知識管理 ====================
from .academic import (  # 學術研究領域; 學術出版和同行評議; 知識管理和本體論; 數據管理和元數據; 研究倫理和合規; 學術評估和指標; 學術會議和活動; 知識產權和授權; 研究合作和網絡
    AccessLevel,
    CitationMetric,
    CollaborationType,
    ConferenceRank,
    ConferenceType,
    ConsentType,
    DataFormat,
    DataType,
    EthicsApprovalStatus,
    FundingType,
    ImpactMeasure,
    IntellectualPropertyType,
    JournalRanking,
    KnowledgeType,
    LicenseType,
    MetadataStandard,
    OntologyType,
    ParticipationType,
    PeerReviewType,
    PresentationFormat,
    PublicationType,
    ResearchDiscipline,
    ResearcherRole,
    ResearchEthicsCategory,
    ResearchMethodology,
    ResearchPhase,
    ResearchType,
    ReviewStatus,
    SemanticRelation,
)

# ==================== AI 系統相關 ====================
from .ai import (  # 機器學習模型; 對話系統; RAG 系統; 技能圖分析; 計劃執行; 經驗學習; 能力評估; 跨語言橋接; AI 工作流程; 智能代理; 數據處理
    ActionType,
    AgentRole,
    AgentType,
    AssessmentType,
    CapabilityType,
    ChunkingStrategy,
    CommunicationProtocol,
    ConversationRole,
    ConversationState,
    ConversationTurn,
    DataFlow,
    DataQuality,
    DocumentType,
    EmbeddingModel,
    EvaluationMethod,
    ExecutionStatus,
    ExecutionStrategy,
    ExperienceSource,
    FeedbackType,
    IntentCategory,
    InteroperabilityLevel,
    KnowledgeSource,
    LanguageType,
    LearningPathType,
    LearningType,
    MemoryType,
    MetricType,
    ModelCapability,
    ModelProvider,
    ModelStatus,
    ModelType,
    PerformanceLevel,
    PriorityLevel,
    ProcessingStage,
    ResponseType,
    RetrievalStrategy,
    SkillCategory,
    SkillLevel,
    SkillRelationType,
    TranslationType,
    TriggerType,
    VectorStore,
    WorkflowStatus,
    WorkflowType,
)

# ==================== 通用枚舉 ====================
# ==================== 資產管理 ====================
from .assets import (
    AssetExposure,
    AssetStatus,
    AssetType,
    BusinessCriticality,
    ComplianceFramework,
    DataSensitivity,
    Environment,
)

# ==================== 業務和商業邏輯 ====================
from .business import (  # 業務流程和工作流; 客戶關係管理; 銷售和市場營銷; 產品和服務管理; 財務和會計; 人力資源管理; 供應鏈管理; 風險管理和合規; 品質管理; 戰略管理和治理
    AccountType,
    ApprovalStatus,
    AuditResult,
    BusinessProcessType,
    CampaignStatus,
    CampaignType,
    ComplianceFrameworkType,
    ControlType,
    CustomerSegment,
    CustomerStatus,
    CustomerType,
    DeliveryStatus,
    Department,
    EmployeeStatus,
    EmployeeType,
    GovernanceLevel,
    ImprovementMethodology,
    InteractionType,
    InvoiceStatus,
    LeadSource,
    PaymentMethod,
    PaymentStatus,
    PerformanceRating,
    PricingModel,
    ProcessStatus,
    ProductStatus,
    ProductType,
    PurchaseOrderStatus,
    QualityMetric,
    QualityStandard,
    RiskCategory,
    RiskLevel,
    RiskStatus,
    SalesStage,
    ServiceLevel,
    StrategicObjective,
    SupplierStatus,
    SupplierType,
    TaskType,
    TransactionType,
)
from .common import (
    AlertType,
    AsyncTaskStatus,
    Confidence,
    DataFormat,
    EncodingType,
    ErrorCategory,
    HttpMethod,
    HttpStatusCodeRange,
    LogLevel,
    NetworkProtocol,
    OperationResult,
    PluginStatus,
    PluginType,
    RemediationStatus,
    ResponseDataType,
    RiskLevel,
    ScanStatus,
    ScanStrategy,
    Severity,
    StoppingReason,
    TaskStatus,
    TaskType,
    TestStatus,
    ThreatLevel,
    ValidationResult,
)

# ==================== 數據模型和格式 ====================
from .data_models import (  # 數據格式; JSON Schema; 數據庫模型; API 數據模型; 文件格式; 消息格式; 數據質量; 數據處理; 存儲模式
    AggregationFunction,
    APIDataType,
    CachingStrategy,
    CompressionType,
    ConsistencyLevel,
    ConstraintType,
    DataFormat,
    DataQualityDimension,
    DataType,
    DeliveryMode,
    EncodingType,
    ErrorSeverity,
    EventType,
    FileFormat,
    IndexType,
    IsolationLevel,
    JoinType,
    JSONSchemaFormat,
    JSONSchemaType,
    JSONSchemaValidation,
    MessageFormat,
    MessagePriority,
    PaginationType,
    PartitioningStrategy,
    RelationshipType,
    ResponseStructure,
    SerializationFormat,
    SortOrder,
    TransformationType,
    ValidationLevel,
    ValidationRule,
)

# ==================== 基礎設施和網絡 ====================
from .infrastructure import (  # 網絡協議和服務; 雲端基礎設施; 存儲系統; 安全基礎設施; 監控和觀測; 負載均衡和高可用; 網絡架構模式; 資源管理; 災難恢復; 合規和治理
    AlertSeverity,
    ArchitecturePattern,
    AuthenticationMethod,
    BackupType,
    CertificateType,
    CloudDeploymentModel,
    CloudProvider,
    CloudServiceModel,
    ComplianceFramework,
    ContainerOrchestrator,
    DeploymentStrategy,
    DisasterRecoveryTier,
    EncryptionAlgorithm,
    FirewallAction,
    GovernanceModel,
    HighAvailabilityPattern,
    LoadBalancingAlgorithm,
    LogLevel,
    MetricType,
    MonitoringType,
    NetworkProtocol,
    NetworkSegmentation,
    NetworkTopology,
    PerformanceTier,
    PortType,
    RAIDLevel,
    RecoveryMetric,
    ResourceState,
    ResourceType,
    ScalingType,
    ServiceMeshType,
    StorageInterface,
    StorageType,
)

# ==================== 模組相關 ====================
from .modules import (
    CodeQualityMetric,
    ECMAScriptVersion,
    JavaScriptFeature,
    LanguageFramework,
    ModuleName,
    ProgrammingLanguage,
    Topic,
)

# ==================== 系統操作和運維 ====================
from .operations import (  # DevOps 和 CI/CD; 測試類型和策略; 事件管理和操作; 性能和資源監控; 自動化和編排; 服務品質和SLA; 運維工具和平台; 敏捷和項目管理; 品質保證和合規; 容量規劃和優化
    AgileMethodology,
    AgileTaskStatus,
    AuditType,
    AutomationType,
    BuildStatus,
    CapacityMetric,
    CapacityPlanningMethod,
    ChangeStatus,
    ChangeType,
    ComplianceStatus,
    ConfigurationTool,
    ContainerTool,
    DeploymentEnvironment,
    DevOpsStage,
    IncidentCategory,
    IncidentSeverity,
    IncidentStatus,
    MonitoringTool,
    OptimizationType,
    OrchestrationTool,
    PerformanceMetric,
    PipelineStage,
    PriorityLevel,
    QualityGate,
    ReleaseType,
    ResourceOptimizationStrategy,
    ScheduleType,
    ServiceLevel,
    SLAMetric,
    SprintStatus,
    TeamRole,
    TestingStrategy,
    TestLevel,
    TestResult,
    TestType,
    ThresholdType,
    WorkflowStatus,
)

# ==================== 滲透測試系統 ====================
from .pentest import (  # OWASP 標準; MITRE ATT&CK; 滲透測試階段; 漏洞掃描; Web 安全; 網絡安全; 移動安全; 雲安全; 社會工程; 物理安全; 無線安全; 報告和合規; 威脅建模; 工具和自動化
    AssetType,
    AuthenticationMethod,
    AutomationLevel,
    CloudProvider,
    CloudServiceType,
    CloudTestArea,
    ComplianceFramework,
    EvidenceType,
    ExploitationType,
    FalsePositiveRisk,
    HTTPTestMethod,
    InformationGatheringMethod,
    MITREMatrix,
    MITREPlatform,
    MITRETactic,
    MobilePlatform,
    MobileTestCategory,
    MobileVulnerabilityType,
    NetworkProtocol,
    NetworkTestType,
    OWASPRiskRating,
    OWASPTestingCategory,
    OWASPTop10,
    PentestPhase,
    PentestTool,
    PhysicalTestType,
    PortState,
    PostExploitationGoal,
    ReconnaissanceType,
    ReportType,
    ScanDepth,
    ScanType,
    SocialEngineeringType,
    SocialEngineeringVector,
    TestExecutionMode,
    ThreatCategory,
    ThreatModelingMethodology,
    ValidationMethod,
    WebVulnerabilityType,
    WirelessAttackType,
    WirelessSecurity,
    WirelessStandard,
)

# ==================== 安全測試 ====================
from .security import (  # STIX/TAXII 威脅情報標準; HackerOne 優化相關
    AccessDecision,
    AttackPathEdgeType,
    AttackPathNodeType,
    AttackTactic,
    AttackTechnique,
    BountyPriorityTier,
    BugBountyCategory,
    CVSSAttackComplexity,
    CVSSAttackVector,
    CVSSAvailabilityImpact,
    CVSSConfidentialityImpact,
    CVSSIntegrityImpact,
    CVSSMetric,
    CVSSPrivilegesRequired,
    CVSSUserInteraction,
    CVSSVersion,
    CWECategory,
    Exploitability,
    IntelSource,
    IOCType,
    Location,
    LowValueVulnerabilityType,
    MalwareType,
    MITREPlatform,
    Permission,
    PersistenceType,
    PostExTestType,
    ProgramType,
    RemediationType,
    ResponseTimeCategory,
    SecurityPattern,
    SensitiveInfoType,
    STIXObjectType,
    STIXRelationshipType,
    TAXIIMediaType,
    TestingApproach,
    ThreatActorType,
    TLPMarking,
    ToolType,
    VulnerabilityByLanguage,
    VulnerabilityDifficulty,
    VulnerabilityDisclosure,
    VulnerabilityStatus,
    VulnerabilityType,
)

# ==================== 用戶界面和用戶體驗 ====================
from .ui_ux import (  # 用戶界面元素; 用戶交互模式; 響應式設計; 無障礙設計; 視覺設計系統; 動畫和過渡; 表單設計; 數據可視化; 用戶體驗指標
    AccessibilityLevel,
    AccessibilityRole,
    AnimationDuration,
    AnimationType,
    ButtonType,
    ChartType,
    ColorContrastRatio,
    ColorPalette,
    ColorScheme,
    DataVisualizationPurpose,
    DeviceType,
    EasingFunction,
    Elevation,
    FeedbackType,
    FieldSize,
    FormLayout,
    InputType,
    InteractionPattern,
    InteractionType,
    KeyboardNavigation,
    LayoutType,
    NavigationPattern,
    Orientation,
    PersonaType,
    ScreenSize,
    SpacingSystem,
    TransitionTrigger,
    Typography,
    UIComponentType,
    UserFeedbackType,
    UXMetric,
    ValidationState,
    ValidationTiming,
    ViewportUnit,
)

# ==================== Web API 標準 ====================
from .web_api_standards import (
    HTTPStatusCode,
    JSONSchemaKeyword,
    JWTAlgorithm,
    JWTClaim,
    OpenAPIFormat,
    OpenAPIParameterLocation,
    OpenAPISchemaType,
    OpenAPISecuritySchemeType,
    SARIFArtifactRoles,
    SARIFLevel,
    SARIFResultKind,
    WebStandard,
)

# 為了保持向後相容，明確匯出所有公開介面
__all__ = [
    "AccessDecision",
    "AlertType",
    "AssetExposure",
    "AssetStatus",
    "AssetType",
    "AsyncTaskStatus",
    "AttackPathEdgeType",
    "AttackPathNodeType",
    "AttackTactic",
    "AttackTechnique",
    "BusinessCriticality",
    "CodeQualityMetric",
    "ComplianceFramework",
    "Confidence",
    "CVSSMetric",
    "CWECategory",
    "DataFormat",
    "DataSensitivity",
    "ECMAScriptVersion",
    "EncodingType",
    "Environment",
    "ErrorCategory",
    "Exploitability",
    "HTTPStatusCode",
    "HttpMethod",
    "HttpStatusCodeRange",
    "IOCType",
    "IntelSource",
    "JavaScriptFeature",
    "JSONSchemaKeyword",
    "JWTAlgorithm",
    "JWTClaim",
    "LanguageFramework",
    "Location",
    "NetworkProtocol",
    "LogLevel",
    "ModuleName",
    "OpenAPIFormat",
    "OpenAPIParameterLocation",
    "OpenAPISchemaType",
    "OpenAPISecuritySchemeType",
    "OperationResult",
    "Permission",
    "PersistenceType",
    "PluginStatus",
    "PluginType",
    "PostExTestType",
    "ProgrammingLanguage",
    "RemediationStatus",
    "RemediationType",
    "ResponseDataType",
    "RiskLevel",
    "SARIFArtifactRoles",
    "SARIFLevel",
    "SARIFResultKind",
    "ScanStatus",
    "ScanStrategy",
    "SecurityPattern",
    "SensitiveInfoType",
    "Severity",
    "StoppingReason",
    "TaskStatus",
    "TaskType",
    "TestStatus",
    "ThreatLevel",
    "Topic",
    "ValidationResult",
    "VulnerabilityByLanguage",
    "VulnerabilityStatus",
    "VulnerabilityType",
    "WebStandard",
    # STIX/TAXII 威脅情報標準
    "STIXObjectType",
    "STIXRelationshipType",
    "TLPMarking",
    "MITREPlatform",
    "TAXIIMediaType",
    "CVSSVersion",
    "CVSSAttackVector",
    "CVSSAttackComplexity",
    "CVSSPrivilegesRequired",
    "CVSSUserInteraction",
    "CVSSConfidentialityImpact",
    "CVSSIntegrityImpact",
    "CVSSAvailabilityImpact",
    "VulnerabilityDisclosure",
    "ThreatActorType",
    "MalwareType",
    "ToolType",
    # HackerOne 優化相關
    "BugBountyCategory",
    "BountyPriorityTier",
    "VulnerabilityDifficulty",
    "TestingApproach",
    "ProgramType",
    "ResponseTimeCategory",
    "LowValueVulnerabilityType",
]

# 版本資訊
__version__ = "2.1.0"
