"""
AIVA Common Enums Package

此套件提供了 AIVA 微服務生態系統中所有枚舉類型的統一介面。

使用方式:
    from aiva_common.enums import ModuleName, Severity, VulnerabilityType

架構說明:
    - common.py: 通用枚舉 (狀態、級別等)
    - modules.py: 模組相關枚舉 (模組名稱、主題)
    - security.py: 安全測試枚舉 (漏洞、攻擊類型等)
    - assets.py: 資產管理枚舉 (資產類型、環境等)
"""

# ==================== 通用枚舉 ====================
# ==================== 資產管理 ====================
from .assets import (
    AssetExposure,
    AssetStatus,
    AssetType,
    BusinessCriticality,
    ComplianceFramework,
    DataSensitivity,
    Environment,
)
from .common import (
    AlertType,
    AsyncTaskStatus,
    Confidence,
    DataFormat,
    EncodingType,
    ErrorCategory,
    HttpMethod,
    HttpStatusCodeRange,
    LogLevel,
    NetworkProtocol,
    OperationResult,
    PluginStatus,
    PluginType,
    RemediationStatus,
    ResponseDataType,
    RiskLevel,
    ScanStatus,
    ScanStrategy,
    Severity,
    StoppingReason,
    TaskStatus,
    TaskType,
    TestStatus,
    ThreatLevel,
    ValidationResult,
)

# ==================== 模組相關 ====================
from .modules import (
    CodeQualityMetric,
    ECMAScriptVersion,
    JavaScriptFeature,
    LanguageFramework,
    ModuleName,
    ProgrammingLanguage,
    Topic,
)

# ==================== 安全測試 ====================
from .security import (
    AccessDecision,
    AttackPathEdgeType,
    AttackPathNodeType,
    AttackTactic,
    AttackTechnique,
    CVSSMetric,
    CWECategory,
    Exploitability,
    IntelSource,
    IOCType,
    Location,
    Permission,
    PersistenceType,
    PostExTestType,
    RemediationType,
    SecurityPattern,
    SensitiveInfoType,
    VulnerabilityByLanguage,
    VulnerabilityStatus,
    VulnerabilityType,
    # STIX/TAXII 威脅情報標準
    STIXObjectType,
    STIXRelationshipType,
    TLPMarking,
    MITREPlatform,
    TAXIIMediaType,
    CVSSVersion,
    CVSSAttackVector,
    CVSSAttackComplexity,
    CVSSPrivilegesRequired,
    CVSSUserInteraction,
    CVSSConfidentialityImpact,
    CVSSIntegrityImpact,
    CVSSAvailabilityImpact,
    VulnerabilityDisclosure,
    ThreatActorType,
    MalwareType,
    ToolType,
    # HackerOne 優化相關
    BugBountyCategory,
    BountyPriorityTier,
    VulnerabilityDifficulty,
    TestingApproach,
    ProgramType,
    ResponseTimeCategory,
    LowValueVulnerabilityType,
)

# ==================== Web API 標準 ====================
from .web_api_standards import (
    HTTPStatusCode,
    JSONSchemaKeyword,
    JWTAlgorithm,
    JWTClaim,
    OpenAPIFormat,
    OpenAPIParameterLocation,
    OpenAPISchemaType,
    OpenAPISecuritySchemeType,
    SARIFArtifactRoles,
    SARIFLevel,
    SARIFResultKind,
    WebStandard,
)

# 為了保持向後相容，明確匯出所有公開介面
__all__ = [
    "AccessDecision",
    "AlertType",
    "AssetExposure",
    "AssetStatus",
    "AssetType",
    "AsyncTaskStatus",
    "AttackPathEdgeType", 
    "AttackPathNodeType",
    "AttackTactic",
    "AttackTechnique",
    "BusinessCriticality",
    "CodeQualityMetric",
    "ComplianceFramework",
    "Confidence",
    "CVSSMetric",
    "CWECategory",
    "DataFormat",
    "DataSensitivity",
    "ECMAScriptVersion",
    "EncodingType",
    "Environment",
    "ErrorCategory",
    "Exploitability", 
    "HTTPStatusCode",
    "HttpMethod",
    "HttpStatusCodeRange",
    "IOCType",
    "IntelSource",
    "JavaScriptFeature",
    "JSONSchemaKeyword",
    "JWTAlgorithm",
    "JWTClaim",
    "LanguageFramework",
    "Location",
    "NetworkProtocol",
    "LogLevel",
    "ModuleName",
    "OpenAPIFormat",
    "OpenAPIParameterLocation",
    "OpenAPISchemaType",
    "OpenAPISecuritySchemeType",
    "OperationResult",
    "Permission",
    "PersistenceType",
    "PluginStatus",
    "PluginType",
    "PostExTestType",
    "ProgrammingLanguage",
    "RemediationStatus",
    "RemediationType",
    "ResponseDataType",
    "RiskLevel",
    "SARIFArtifactRoles",
    "SARIFLevel",
    "SARIFResultKind",
    "ScanStatus",
    "ScanStrategy",
    "SecurityPattern",
    "SensitiveInfoType",
    "Severity",
    "StoppingReason",
    "TaskStatus",
    "TaskType",
    "TestStatus",
    "ThreatLevel",
    "Topic",
    "ValidationResult",
    "VulnerabilityByLanguage",
    "VulnerabilityStatus",
    "VulnerabilityType",
    "WebStandard",
    # STIX/TAXII 威脅情報標準
    "STIXObjectType",
    "STIXRelationshipType",
    "TLPMarking",
    "MITREPlatform",
    "TAXIIMediaType",
    "CVSSVersion",
    "CVSSAttackVector",
    "CVSSAttackComplexity",
    "CVSSPrivilegesRequired",
    "CVSSUserInteraction",
    "CVSSConfidentialityImpact",
    "CVSSIntegrityImpact",
    "CVSSAvailabilityImpact",
    "VulnerabilityDisclosure",
    "ThreatActorType",
    "MalwareType",
    "ToolType",
    # HackerOne 優化相關
    "BugBountyCategory",
    "BountyPriorityTier",
    "VulnerabilityDifficulty",
    "TestingApproach",
    "ProgramType",
    "ResponseTimeCategory",
    "LowValueVulnerabilityType",
]

# 版本資訊
__version__ = "2.1.0"

