# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aiva_services_pb2 as aiva__services__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aiva_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """=============================================
    服務定義
    =============================================

    AI 服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeCommand = channel.unary_unary(
                '/aiva.services.AIService/AnalyzeCommand',
                request_serializer=aiva__services__pb2.CommandAnalysisRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.CommandAnalysisResponse.FromString,
                _registered_method=True)
        self.ExecuteReasoning = channel.unary_unary(
                '/aiva.services.AIService/ExecuteReasoning',
                request_serializer=aiva__services__pb2.ReasoningRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.ReasoningResponse.FromString,
                _registered_method=True)
        self.StreamReasoning = channel.unary_stream(
                '/aiva.services.AIService/StreamReasoning',
                request_serializer=aiva__services__pb2.ReasoningRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.ReasoningResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """=============================================
    服務定義
    =============================================

    AI 服務
    """

    def AnalyzeCommand(self, request, context):
        """分析命令意圖
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteReasoning(self, request, context):
        """執行推理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReasoning(self, request, context):
        """流式推理（支援長時間推理）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCommand,
                    request_deserializer=aiva__services__pb2.CommandAnalysisRequest.FromString,
                    response_serializer=aiva__services__pb2.CommandAnalysisResponse.SerializeToString,
            ),
            'ExecuteReasoning': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteReasoning,
                    request_deserializer=aiva__services__pb2.ReasoningRequest.FromString,
                    response_serializer=aiva__services__pb2.ReasoningResponse.SerializeToString,
            ),
            'StreamReasoning': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReasoning,
                    request_deserializer=aiva__services__pb2.ReasoningRequest.FromString,
                    response_serializer=aiva__services__pb2.ReasoningResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiva.services.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiva.services.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """=============================================
    服務定義
    =============================================

    AI 服務
    """

    @staticmethod
    def AnalyzeCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.AIService/AnalyzeCommand',
            aiva__services__pb2.CommandAnalysisRequest.SerializeToString,
            aiva__services__pb2.CommandAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteReasoning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.AIService/ExecuteReasoning',
            aiva__services__pb2.ReasoningRequest.SerializeToString,
            aiva__services__pb2.ReasoningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReasoning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiva.services.AIService/StreamReasoning',
            aiva__services__pb2.ReasoningRequest.SerializeToString,
            aiva__services__pb2.ReasoningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SecurityScannerStub(object):
    """安全掃描服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScan = channel.unary_unary(
                '/aiva.services.SecurityScanner/StartScan',
                request_serializer=aiva__services__pb2.ScanRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.ScanResult.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/aiva.services.SecurityScanner/GetScanStatus',
                request_serializer=aiva__services__pb2.ScanRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.ScanResult.FromString,
                _registered_method=True)
        self.StreamScanResults = channel.unary_stream(
                '/aiva.services.SecurityScanner/StreamScanResults',
                request_serializer=aiva__services__pb2.ScanRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.Finding.FromString,
                _registered_method=True)


class SecurityScannerServicer(object):
    """安全掃描服務
    """

    def StartScan(self, request, context):
        """啟動掃描
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanStatus(self, request, context):
        """獲取掃描狀態
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScanResults(self, request, context):
        """流式掃描結果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityScannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=aiva__services__pb2.ScanRequest.FromString,
                    response_serializer=aiva__services__pb2.ScanResult.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=aiva__services__pb2.ScanRequest.FromString,
                    response_serializer=aiva__services__pb2.ScanResult.SerializeToString,
            ),
            'StreamScanResults': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScanResults,
                    request_deserializer=aiva__services__pb2.ScanRequest.FromString,
                    response_serializer=aiva__services__pb2.Finding.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiva.services.SecurityScanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiva.services.SecurityScanner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityScanner(object):
    """安全掃描服務
    """

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.SecurityScanner/StartScan',
            aiva__services__pb2.ScanRequest.SerializeToString,
            aiva__services__pb2.ScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.SecurityScanner/GetScanStatus',
            aiva__services__pb2.ScanRequest.SerializeToString,
            aiva__services__pb2.ScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScanResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiva.services.SecurityScanner/StreamScanResults',
            aiva__services__pb2.ScanRequest.SerializeToString,
            aiva__services__pb2.Finding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataAnalyzerStub(object):
    """數據分析服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeData = channel.unary_unary(
                '/aiva.services.DataAnalyzer/AnalyzeData',
                request_serializer=aiva__services__pb2.DataAnalysisRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.DataAnalysisResult.FromString,
                _registered_method=True)
        self.StreamAnalysis = channel.unary_stream(
                '/aiva.services.DataAnalyzer/StreamAnalysis',
                request_serializer=aiva__services__pb2.DataAnalysisRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.AnalysisInsight.FromString,
                _registered_method=True)


class DataAnalyzerServicer(object):
    """數據分析服務
    """

    def AnalyzeData(self, request, context):
        """執行數據分析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalysis(self, request, context):
        """流式分析結果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeData': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeData,
                    request_deserializer=aiva__services__pb2.DataAnalysisRequest.FromString,
                    response_serializer=aiva__services__pb2.DataAnalysisResult.SerializeToString,
            ),
            'StreamAnalysis': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalysis,
                    request_deserializer=aiva__services__pb2.DataAnalysisRequest.FromString,
                    response_serializer=aiva__services__pb2.AnalysisInsight.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiva.services.DataAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiva.services.DataAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataAnalyzer(object):
    """數據分析服務
    """

    @staticmethod
    def AnalyzeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.DataAnalyzer/AnalyzeData',
            aiva__services__pb2.DataAnalysisRequest.SerializeToString,
            aiva__services__pb2.DataAnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiva.services.DataAnalyzer/StreamAnalysis',
            aiva__services__pb2.DataAnalysisRequest.SerializeToString,
            aiva__services__pb2.AnalysisInsight.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CodeGeneratorStub(object):
    """代碼生成服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCode = channel.unary_unary(
                '/aiva.services.CodeGenerator/GenerateCode',
                request_serializer=aiva__services__pb2.CodeGenerationRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.CodeGenerationResult.FromString,
                _registered_method=True)
        self.ValidateCode = channel.unary_unary(
                '/aiva.services.CodeGenerator/ValidateCode',
                request_serializer=aiva__services__pb2.CodeGenerationRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.ResponseStatus.FromString,
                _registered_method=True)


class CodeGeneratorServicer(object):
    """代碼生成服務
    """

    def GenerateCode(self, request, context):
        """生成代碼
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCode(self, request, context):
        """驗證生成的代碼
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCode,
                    request_deserializer=aiva__services__pb2.CodeGenerationRequest.FromString,
                    response_serializer=aiva__services__pb2.CodeGenerationResult.SerializeToString,
            ),
            'ValidateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCode,
                    request_deserializer=aiva__services__pb2.CodeGenerationRequest.FromString,
                    response_serializer=aiva__services__pb2.ResponseStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiva.services.CodeGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiva.services.CodeGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeGenerator(object):
    """代碼生成服務
    """

    @staticmethod
    def GenerateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.CodeGenerator/GenerateCode',
            aiva__services__pb2.CodeGenerationRequest.SerializeToString,
            aiva__services__pb2.CodeGenerationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.CodeGenerator/ValidateCode',
            aiva__services__pb2.CodeGenerationRequest.SerializeToString,
            aiva__services__pb2.ResponseStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WebServiceStub(object):
    """Web 服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleRequest = channel.unary_unary(
                '/aiva.services.WebService/HandleRequest',
                request_serializer=aiva__services__pb2.HttpRequestInfo.SerializeToString,
                response_deserializer=aiva__services__pb2.HttpResponseInfo.FromString,
                _registered_method=True)
        self.ScanWebsite = channel.unary_stream(
                '/aiva.services.WebService/ScanWebsite',
                request_serializer=aiva__services__pb2.ScanRequest.SerializeToString,
                response_deserializer=aiva__services__pb2.WebScanResult.FromString,
                _registered_method=True)


class WebServiceServicer(object):
    """Web 服務
    """

    def HandleRequest(self, request, context):
        """處理 HTTP 請求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanWebsite(self, request, context):
        """執行 Web 掃描
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleRequest,
                    request_deserializer=aiva__services__pb2.HttpRequestInfo.FromString,
                    response_serializer=aiva__services__pb2.HttpResponseInfo.SerializeToString,
            ),
            'ScanWebsite': grpc.unary_stream_rpc_method_handler(
                    servicer.ScanWebsite,
                    request_deserializer=aiva__services__pb2.ScanRequest.FromString,
                    response_serializer=aiva__services__pb2.WebScanResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiva.services.WebService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiva.services.WebService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebService(object):
    """Web 服務
    """

    @staticmethod
    def HandleRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiva.services.WebService/HandleRequest',
            aiva__services__pb2.HttpRequestInfo.SerializeToString,
            aiva__services__pb2.HttpResponseInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanWebsite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiva.services.WebService/ScanWebsite',
            aiva__services__pb2.ScanRequest.SerializeToString,
            aiva__services__pb2.WebScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
