# AIVA Rust Analysis CLI Commands

## Category: ANALYSIS
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::analyze_robots
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::analyze_sitemap
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::analyze
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::extract_api_endpoints
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::find_line_number
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::mask_key

## Category: EXPLOITATION
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func AttackSurfaceAssessor::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func AttackSurfaceAssessor::assess
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func AttackSurfaceAssessor::calculate_risk_distribution
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func AttackSurfaceAssessor::identify_high_risk_targets
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func AttackSurfaceAssessor::recommend_tests
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func AttackSurfaceAssessor::generate_summary

## Category: OTHER
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func RiskCalculator::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func RiskCalculator::calculate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func EngineRecommender::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func EngineRecommender::recommend
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func EngineRecommender::has_spa_indicators
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\attack_surface.rs --func EngineRecommender::has_cloud_indicators
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::with_auth_type
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::load_default_credentials
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::spray
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::test_credential
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::test_basic_auth
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::test_form_based
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::test_json_api
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::discover
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::extract_endpoints_from_js
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::calculate_path_risk
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::extract_robots_path
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::extract_sitemap_urls
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func main
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func fetch_page_content
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func deduplicate_findings
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Severity::fmt
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Severity::from_str
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Confidence::fmt
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Confidence::from_str
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingStatus::fmt
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingStatus::from_str
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskStatus::fmt
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskStatus::from_str
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginStatus::fmt
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginStatus::from_str
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginType::fmt
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginType::from_str
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func MessageHeader::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func MessageHeader::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func MessageHeader::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Target::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Target::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Target::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Vulnerability::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Vulnerability::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Vulnerability::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Asset::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Asset::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Asset::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Authentication::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Authentication::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Authentication::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ExecutionError::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ExecutionError::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ExecutionError::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Fingerprints::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Fingerprints::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Fingerprints::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RateLimit::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RateLimit::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RateLimit::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RiskFactor::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RiskFactor::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RiskFactor::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Summary::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Summary::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func Summary::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func TaskDependency::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func TaskDependency::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func TaskDependency::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVerificationRequest::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVerificationRequest::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVerificationRequest::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVerificationResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVerificationResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVerificationResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CodeLevelRootCause::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CodeLevelRootCause::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CodeLevelRootCause::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingTarget::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingTarget::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingTarget::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func JavaScriptAnalysisResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func JavaScriptAnalysisResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func JavaScriptAnalysisResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func SASTDASTCorrelation::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func SASTDASTCorrelation::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func SASTDASTCorrelation::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func SensitiveMatch::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func SensitiveMatch::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func SensitiveMatch::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func VulnerabilityCorrelation::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func VulnerabilityCorrelation::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func VulnerabilityCorrelation::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AivaMessage::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AivaMessage::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AivaMessage::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVARequest::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVARequest::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVARequest::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVAResponse::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVAResponse::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AIVAResponse::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskPayload::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskPayload::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskPayload::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskTarget::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskTarget::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskTarget::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskContext::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskContext::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskContext::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskTestConfig::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskTestConfig::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FunctionTaskTestConfig::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingPayload::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingPayload::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingPayload::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingEvidence::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingEvidence::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingEvidence::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingImpact::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingImpact::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingImpact::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingRecommendation::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingRecommendation::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func FindingRecommendation::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func TokenTestResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func TokenTestResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func TokenTestResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RetryConfig::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RetryConfig::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func RetryConfig::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ResourceLimits::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ResourceLimits::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ResourceLimits::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskConfig::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskConfig::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskConfig::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncTaskResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncBatchConfig::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncBatchConfig::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncBatchConfig::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncBatchResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncBatchResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func AsyncBatchResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginManifest::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginManifest::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginManifest::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginExecutionContext::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginExecutionContext::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginExecutionContext::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginExecutionResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginExecutionResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginExecutionResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginConfig::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginConfig::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginConfig::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginRegistry::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginRegistry::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginRegistry::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginHealthCheck::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginHealthCheck::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func PluginHealthCheck::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIParameter::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIParameter::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIParameter::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLICommand::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLICommand::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLICommand::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIExecutionResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIExecutionResult::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIExecutionResult::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLISession::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLISession::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLISession::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIConfiguration::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIConfiguration::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIConfiguration::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIMetrics::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIMetrics::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func CLIMetrics::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func VerificationResult::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func VerificationResult::with_metadata
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::with_cache_ttl
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::hash_secret
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::get_cached
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::cache_result
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::cleanup_cache
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_aws
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_github
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_slack
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_stripe
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_twilio
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_sendgrid
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_mailgun
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_digitalocean
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_cloudflare
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::verify_datadog
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\verifier.rs --func Verifier::default

## Category: RECONNAISSANCE
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\auth_brute.rs --func CredentialSprayer::detect_auth_type
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\endpoint_discovery.rs --func EndpointDiscoverer::scan_common_paths
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::detect_api_key_leaks
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::detect_internal_domains
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\js_analyzer.rs --func JsAnalyzer::detect_sensitive_comments
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func ScanMode::from
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func scan_targets
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func scan_single_target
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func detect_technologies_from_content
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::with_mode
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::scan
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::scan_fast
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::scan_deep
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::scan_focused
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\scanner.rs --func SensitiveInfoScanner::mask_sensitive
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ScanScope::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ScanScope::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ScanScope::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ScanTaskPayload::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ScanTaskPayload::validate
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\schemas\generated\mod.rs --func ScanTaskPayload::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func SecretDetector::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func SecretDetector::load_default_rules
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func SecretDetector::scan_content
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func SecretDetector::extract_context
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func SecretDetector::redact_secret
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func EntropyDetector::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func EntropyDetector::detect_line
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func EntropyDetector::calculate_entropy
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\secret_detector.rs --func SecretDetector::default
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::new
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::with_timeout
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::detect
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::test_te_cl
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::test_cl_te
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::send_payload
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::analyze_response
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\smuggling_detector.rs --func SmugglingDetector::differential_test

## Category: REPORTING
cargo run --bin rs2mermaid -- --file C:\D\fold7\AIVA-git\services\scan\rust_engine\src\main.rs --func generate_summary

