# AIVA TypeScript Analysis CLI Commands
# Auto-generated by ts2mermaid

## Category: ANALYSIS
# [PLACEHOLDER] Stitcher.analyzeBranches in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.analyzeBranches"

# [PLACEHOLDER] parseImports in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "parseImports"

## Category: OTHER
# [PLACEHOLDER] ensureDirectories in paths.config.ts
npx ts-node ts2mermaid.ts --file "paths.config.ts" --func "ensureDirectories"

# [PLACEHOLDER] getAnalysisOutputDir in paths.config.ts
npx ts-node ts2mermaid.ts --file "paths.config.ts" --func "getAnalysisOutputDir"

# [PLACEHOLDER] getDefaultOutputDir in paths.config.ts
npx ts-node ts2mermaid.ts --file "paths.config.ts" --func "getDefaultOutputDir"

# [PLACEHOLDER] getConfigSummary in paths.config.ts
npx ts-node ts2mermaid.ts --file "paths.config.ts" --func "getConfigSummary"

# [PLACEHOLDER] GraphNode.sanitizeId in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "GraphNode.sanitizeId"

# [PLACEHOLDER] Graph.add in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Graph.add"

# [PLACEHOLDER] Graph.link in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Graph.link"

# [PLACEHOLDER] Graph.toMermaid in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Graph.toMermaid"

# [PLACEHOLDER] Graph.formatNode in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Graph.formatNode"

# [PLACEHOLDER] Graph.formatEdge in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Graph.formatEdge"

# [PLACEHOLDER] Stitcher.addScript in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.addScript"

# [PLACEHOLDER] Stitcher.resolveConnections in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.resolveConnections"

# [PLACEHOLDER] Stitcher.findProvider in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.findProvider"

# [PLACEHOLDER] Stitcher.checkCandidates in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.checkCandidates"

# [PLACEHOLDER] Stitcher.sanitizeId in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.sanitizeId"

# [PLACEHOLDER] Builder.build in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.build"

# [PLACEHOLDER] Builder.extractParams in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.extractParams"

# [PLACEHOLDER] Builder.visitBlock in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.visitBlock"

# [PLACEHOLDER] Builder.visitNode in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.visitNode"

# [PLACEHOLDER] Builder.handleIf in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.handleIf"

# [PLACEHOLDER] Builder.handleLoop in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.handleLoop"

# [PLACEHOLDER] Builder.handleReturn in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.handleReturn"

# [PLACEHOLDER] Builder.handleCall in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Builder.handleCall"

# [PLACEHOLDER] Classifier.classify in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Classifier.classify"

# [PLACEHOLDER] Classifier.getResult in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Classifier.getResult"

# [PLACEHOLDER] getAllFiles in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "getAllFiles"

# [PLACEHOLDER] visit in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "visit"

# [PLACEHOLDER] processFile in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "processFile"

# [PLACEHOLDER] visit in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "visit"

# [PLACEHOLDER] main in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "main"

# [PLACEHOLDER] getArg in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "getArg"

# [PLACEHOLDER] convertConnectionsToFlows in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "convertConnectionsToFlows"

## Category: REPORTING
# [PLACEHOLDER] Stitcher.generateSystemFlow in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "Stitcher.generateSystemFlow"

# [PLACEHOLDER] generateCLI in ts2mermaid.ts
npx ts-node ts2mermaid.ts --file "ts2mermaid.ts" --func "generateCLI"

