flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;獲取配置摘要（用於日誌輸出）&amp;&#35;39;]
    n4[crawl = self._config.crawlin...]
    n5[dynamic = self._config.dynamic]
    n6[perf = self._config.perform...]
    n7[lines = &#91;&amp;&#35;39;Configuration Summ...]
    n8[return &amp;&#35;39;\n&amp;&#35;39;.join&#40;lines&#41;]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 --> n8
    n8 --> n2