flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        將配置轉換為字典\n\n        Returns:\n    ...]
    n4[return &#123;&amp;&#35;39;user_headers&amp;&#35;39;: self...]
    n1 --> n3
    n3 --> n4
    n4 --> n2