flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        從字典創建配置\n\n        Args:\n        ...]
    n4[return cls&#40;user_headers=config_dict.g...]
    n1 --> n3
    n3 --> n4
    n4 --> n2