flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        添加資產到收集列表\n\n        Args:\n      ...]
    n4[self.assets.append&#40;asset&#41;]
    n5[logger.debug&#40;f&amp;&#35;39;Asset added: &#123;asset.t...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2