flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;\n        檢查主機名是否被允許\n\n        Args:\n     ...]
    n4[return self._is_host_allowed&#40;hostname...]
    n1 --> n3
    n3 --> n4
    n4 --> n2