flowchart TB
    n1([開始])
    n2([結束])
    n3[&amp;&#35;39;清空所有匹配記錄&amp;&#35;39;]
    n4[self.matches.clear&#40;&#41;]
    n5[logger.debug&#40;&amp;&#35;39;Cleared all sensitive data ...]
    n1 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n2